# Bozeman + Kitchener water breaks & Mains

### Cleaning of Bozeman dataset

This notebook will be for cleaning and pre-processing at the next step for the Bozeman and kitchener datasets

The goal is
- to understand the datatypes that each dataset holds
- clean and drop out columns or rows that are not relevant for analysis
- identify where they can be linked for analysis
- get all cleaned ready for preprocessing

### An overview of the dataset

- information about break date, installation date, pipe size,type of leak are critical for analysis

In [ ]:
# importing the datasets

import pandas as pd
bozemanDataFrame = pd.read_csv("data/Bozeman_watermainbreaks.csv")
kitchenerWaterMainBreaksDf = pd.read_csv("data/Kitchener_watermainbreaks.csv")
kitchenerWaterMainsDf = pd.read_csv("data/Kitchener_watermains.csv")

# print the first 10 rows of each dataset
print("=== Bozeman Water Main Breaks Dataset ===")
print(bozemanDataFrame.head(10).to_string())
print("\n")
print("=== Kitchener Water Main Breaks Dataset ===")
print(kitchenerWaterMainBreaksDf.head(10).to_string())
print("\n")
print("=== Kitchener Water Mains Dataset ===")
print(kitchenerWaterMainsDf.head(10).to_string())

=== Bozeman Water Main Breaks Dataset ===
               X             Y  OBJECTID_1              Break_Date                              Address  Pipe_Size                     Type_of_Leak     Cost     WOID   FACID  PIPE_INSTALL_DA Detected
0  496675.559596  5.058910e+06           1  2013/01/28 00:00:00+00                            431 N 4TH        6.0                        Corrosion  3273.33  86318.0   334.0           1948.0       No
1  496631.156500  5.059796e+06           2  2012/08/11 00:00:00+00                   1126 N 7TH (KMART)        8.0               Longitudinal Break   286.10  80400.0   204.0           1974.0       No
2  496352.228196  5.060142e+06           3  2002/02/15 00:00:00+00            5 Baxter Lane Holiday Inn        4.0             Pipe Failure at Bend   770.57      NaN   281.0           2001.0       No
3  496383.946396  5.058829e+06           4  1997/07/07 00:00:00+00            Seventh Av N/Villard St W        6.0  Rock in hyd nozzel - hammer N/C  2301.76      NaN   247.0           1963.0       No
4  497775.721701  5.058148e+06           5  2009/05/28 00:00:00+00            S WALLACE AVE& E OLIVE ST        6.0                Full Circle Break  2222.83  32256.0   408.0           1924.0       No
5  496580.986396  5.058832e+06           6  2005/12/14 00:00:00+00                    500 blk W Villard        6.0                Full Circle Break  1325.62      NaN   560.0           1948.0       No
6  498304.274998  5.052474e+06           7  2003/03/28 00:00:00+00                    5000 Sourdough Rd       30.0                  Blown Out Piece  3249.28      NaN  2988.0           1981.0       No
7  498301.959198  5.052292e+06           8  2003/08/07 00:00:00+00  Transmission line by Sourdough Tank       30.0                  Blown Out Piece  1746.54      NaN  2988.0           1981.0       No
8  497263.634397  5.059113e+06           9  2011/05/18 00:00:00+00  Peach St. between Bozeman and Black        6.0                    Leaking Joint  2229.56  46996.0  1179.0           1929.0       No
9  495063.790099  5.058329e+06          10  2008/12/04 00:00:00+00                       1922 W BABCOCK       10.0               Longitudinal Break  7483.67  28592.0  1241.0           1971.0       No


=== Kitchener Water Main Breaks Dataset ===
   OBJECTID  Wat Break Incident ID           Incident date Type of Asset Broken Does the road need to be closed? Does the sidewalk need to be closed? Estimated Hours for Repair Estimated Number of Units Impacted  CW Service Request Number Current status of the break Status last updated date  CW Workorder # Date operations was returned to normal service              Nature of Break Apparent cause of break Repair Type  Type of Planned Maintenance                                  List Valves Closed  List Valves Opened List Hydrants Called Out List Hydrants Called Back In Categorization of the Break  Road Segment ID Closest Civic Number           Street  Related Asset ID  Related Asset Depth (m)  Depth of Frost (m)  Asset Size (cm)  Year Asset Installed Asset Material Asset Exists                              GLOBALID UPDATE_BY            UPDATE_DATE            x             y
0         1                   2252    12/1/2017 3:15:00 PM                 MAIN                 Partially Closed                                 Open                12-16 hours                                 47                   123456.0            REPAIR COMPLETED    12/2/2017 12:00:00 AM        177898.0                          1/31/2017 11:30:00 PM  CORROSION AND FITTING/JOINT                     AGE      CUTOUT                          NaN  6" 93563, 94817, 93902,1139; 18"- 1264, 92862,1142                 NaN                      353                          353                  CATEGORY 2             6961                  125   LANCASTER ST W            134292                      1.6                 0.3            450.0                1937.0             CI            Y  3521d297-1a2e-4e7b-a071-fc53ed87e965  GIS_DATA   10/3/2018 2:42:09 PM  541741.1448  4.812354e+06
1      7874                   1311   3/26/2001 12:00:00 AM              SERVICE                              NaN                                  NaN                        NaN                                NaN                        NaN            REPAIR COMPLETED    12/15/2011 3:38:28 PM             NaN                                            NaN                      UNKNOWN                   OTHER         NaN                          NaN                                                 NaN                 NaN                      NaN                          NaN                  CATEGORY 1             6116                   76  CLOVERDALE CRES           4101323                      NaN                 NaN             13.0                1965.0            XXX            Y  72445d62-16a8-43c1-9733-56b06015b077    DAVIDV  12/15/2011 3:38:28 PM  539253.7576  4.807875e+06
2      7875                   1325    9/6/2006 12:00:00 AM              SERVICE                              NaN                                  NaN                        NaN                                NaN                        NaN            REPAIR COMPLETED    12/15/2011 3:38:28 PM        162230.0                                            NaN                      UNKNOWN                   OTHER         NaN                          NaN                                                 NaN                 NaN                      NaN                          NaN                  CATEGORY 1            13207                   47        WREN CRES           4099987                      NaN                 NaN             25.0                1967.0            XXX            Y  3bdc8931-31c0-4090-a07a-a6847781dd97    DAVIDV  12/15/2011 3:38:28 PM  545329.4589  4.810392e+06
3      7876                   1328   9/11/2006 12:00:00 AM              SERVICE                              NaN                                  NaN                        NaN                                NaN                        NaN            REPAIR COMPLETED    12/15/2011 3:38:28 PM             NaN                                            NaN                      UNKNOWN                   OTHER         NaN                          NaN                                                 NaN                 NaN                      NaN                          NaN                  CATEGORY 1             6498                  382    GREENBROOK DR           4642530                      NaN                 NaN             25.0                1964.0            PVC            Y  f75ad0b1-5b2a-4125-8ad5-2b9a037debd7    DAVIDV  12/15/2011 3:38:28 PM  539592.5208  4.808291e+06
4      7877                   1308   1/27/2000 12:00:00 AM              SERVICE                              NaN                                  NaN                        NaN                                NaN                        NaN            REPAIR COMPLETED    12/15/2011 3:38:28 PM             NaN                                            NaN                      UNKNOWN                   OTHER         NaN                          NaN                                                 NaN                 NaN                      NaN                          NaN                  CATEGORY 1            22846                  224    MONTGOMERY RD           4100648                      NaN                 NaN             25.0                1967.0            XXX            Y  5a3c5d03-0899-4899-95e7-278bc5cbb682    DAVIDV  12/15/2011 3:38:28 PM  543897.8495  4.810175e+06
5      7878                   1312   8/11/1998 12:00:00 AM              SERVICE                              NaN                                  NaN                        NaN                                NaN                        NaN            REPAIR COMPLETED    12/15/2011 3:38:28 PM             NaN                                            NaN                      UNKNOWN                   OTHER         NaN                          NaN                                                 NaN                 NaN                      NaN                          NaN                  CATEGORY 1             5421                  152   WESTHEIGHTS DR           4104575                      NaN                 NaN             25.0                1974.0            XXX            Y  0c575f03-7d3f-44ea-b691-d33a969c4428    DAVIDV  12/15/2011 3:38:28 PM  538063.0983  4.808117e+06
6      7879                   1321   5/23/2006 12:00:00 AM              SERVICE                              NaN                                  NaN                        NaN                                NaN                        NaN            REPAIR COMPLETED    12/15/2011 3:38:28 PM             NaN                                            NaN                      UNKNOWN                   OTHER         NaN                          NaN                                                 NaN                 NaN                      NaN                          NaN                  CATEGORY 1            22124                  NaN       RIVER RD E           4138965                      NaN                 NaN            150.0                1976.0            XXX            Y  e82585b3-df56-4d38-8038-536ef084072b    DAVIDV  12/15/2011 3:38:28 PM  547018.7513  4.808296e+06
7      7880                   1326  10/30/2006 12:00:00 AM              SERVICE                              NaN                                  NaN                        NaN                                NaN                        NaN            REPAIR COMPLETED    12/15/2011 3:38:28 PM             NaN                                            NaN                      UNKNOWN                   OTHER         NaN                          NaN                                                 NaN                 NaN                      NaN                          NaN                  CATEGORY 1           602405                  NaN        BLEAMS RD           4659302                      NaN                 NaN             25.0                2012.0            PVC            N  b8f9e9df-09e7-4013-9acc-0e43065d18df    DAVIDV  12/15/2011 3:38:28 PM  538558.0000  4.805205e+06
8      7881                   2047   3/12/2015 12:00:00 AM              SERVICE                              NaN                                  NaN                        NaN                                NaN                        NaN            REPAIR COMPLETED    4/15/2015 12:00:00 AM        126895.0                                            NaN                      UNKNOWN                   OTHER         NaN                          NaN                                                 NaN                 NaN                      NaN                          NaN                  CATEGORY 1            11399                  251          MILL ST           4101475                      NaN                 NaN              NaN                   NaN            NaN            N  536f67ed-4ec6-470e-b0d2-7e916e639d6a    DAVIDV  4/15/2015 12:00:00 AM  541546.9539  4.809431e+06
9      7882                   1324   6/26/2006 12:00:00 AM              SERVICE                              NaN                                  NaN                        NaN                                NaN                        NaN            REPAIR COMPLETED    12/15/2011 3:38:28 PM             NaN                                            NaN                      UNKNOWN                   OTHER         NaN                          NaN                                                 NaN                 NaN                      NaN                          NaN                  CATEGORY 1            10973                 2969      KINGSWAY DR           4095182                      NaN                 NaN            150.0                1975.0            XXX            Y  04df3fcf-e2a1-448a-93dc-0818ba726403    DAVIDV  12/15/2011 3:38:28 PM  545344.7332  4.808249e+06


=== Kitchener Water Mains Dataset ===
   OBJECTID  WATMAINID  STATUS PRESSURE_ZONE  ROADSEGMENTID         MAP_LABEL CATEGORY  PIPE_SIZE MATERIAL LINED LINED_DATE LINED_MATERIAL     INSTALLATION_DATE ACQUISITION            CONSULTANT             OWNERSHIP BRIDGE_MAIN BRIDGE_DETAILS  CRITICALITY  REL_CLEANING_AREA REL_CLEANING_SUBAREA Undersized Shallow Main  Condition Score OVERSIZED CLEANED  Shape__Length
0     77753      10080  ACTIVE         KIT 6           5457   34.2m 450mm  DI  TREATED        450       DI    NO        NaN           NONE  1/1/1979 12:00:00 AM     DONATED                   NaN  DUAL CITY AND REGION           N            NaN            6                  6                    8          N            N             8.50         N       N      34.210563
1     77754      76299  ACTIVE         KIT 4           6390     .4m 300mm  DI  TREATED        300       DI    NO        NaN           NONE  7/1/1968 12:00:00 AM   PURCHASED                   NaN                REGION           N            NaN            7                  1                    4          N            N             8.50         N       N       0.355118
2     77755      10110  ACTIVE         KIT 6           5393   67.9m 450mm  DI  TREATED        450       DI    NO        NaN           NONE  1/1/1979 12:00:00 AM     DONATED                   NaN  DUAL CITY AND REGION           N            NaN            7                  6                    8          N            N             6.10         N       Y      67.852910
3     77756      82566  ACTIVE         KIT 6           5393      7m 450mm  DI  TREATED        450       DI    NO        NaN           NONE  1/1/1979 12:00:00 AM     DONATED                   NaN  DUAL CITY AND REGION           N            NaN            6                  6                    8          N            N             4.58         N       Y       7.039328
4     77757      82568  ACTIVE         KIT 6           5394     15m 450mm  DI  TREATED        450       DI    NO        NaN           NONE  1/1/1979 12:00:00 AM     DONATED                   NaN  DUAL CITY AND REGION           N            NaN            6                  6                    8          N            N             8.50         N       Y      14.956131
5     77758      10090  ACTIVE         KIT 6           5402   38.5m 450mm  DI  TREATED        450       DI    NO        NaN           NONE  1/1/1979 12:00:00 AM     DONATED                   NaN  DUAL CITY AND REGION           N            NaN            6                  6                    8          N            N             8.50         N       Y      38.526891
6     77759      82570  ACTIVE         KIT 6           5456   12.5m 450mm  DI  TREATED        450       DI    NO        NaN           NONE  1/1/1979 12:00:00 AM     DONATED                   NaN  DUAL CITY AND REGION           N            NaN            6                  6                    7          N            N             8.50         N       N      12.451964
7     77760      10030  ACTIVE         KIT 6          21108    125m 450mm  DI  TREATED        450       DI    NO        NaN           NONE  1/1/1979 12:00:00 AM     DONATED                   NaN  DUAL CITY AND REGION           N            NaN            7                  6                    7          N            N             8.50         N       N     124.970065
8     77761      10100  ACTIVE         KIT 6           5396   55.7m 450mm  DI  TREATED        450       DI    NO        NaN           NONE  1/1/1979 12:00:00 AM     DONATED                   NaN  DUAL CITY AND REGION           N            NaN            6                  6                    8          N            N             8.50         N       Y      55.671581
9     77762      81620  ACTIVE        KIT 2W         102861  63.9m 300mm  PVC  TREATED        300      PVC    NO        NaN           NONE  1/6/2015 12:00:00 AM   PURCHASED  MTE CONSULTANTS INC.             KITCHENER           N            NaN            0                  5                   46          N            N             9.35         N       N      63.948585

### Overview of the 3 datasets

In [164]:
# quick overview of the dataset

print("\nBozeman Water Main Breaks info:")
bozemanDataFrame.info()
print("\nKitchener Water Main Breaks info:")
kitchenerWaterMainBreaksDf.info()
print("\nKitchener Water Mains info:")
kitchenerWaterMainsDf.info()

Bozeman Water Main Breaks info:
<class 'pandas.DataFrame'>
RangeIndex: 158 entries, 0 to 157
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   X                158 non-null    float64
 1   Y                158 non-null    float64
 2   OBJECTID_1       158 non-null    int64
 3   Break_Date       158 non-null    str
 4   Address          153 non-null    str
 5   Pipe_Size        157 non-null    float64
 6   Type_of_Leak     158 non-null    str
 7   Cost             156 non-null    float64
 8   WOID             122 non-null    float64
 9   FACID            157 non-null    float64
 10  PIPE_INSTALL_DA  155 non-null    float64
 11  Detected         158 non-null    str
dtypes: float64(7), int64(1), str(4)
memory usage: 14.9 KB

Kitchener Water Main Breaks info:
<class 'pandas.DataFrame'>
RangeIndex: 2994 entries, 0 to 2993
Data columns (total 37 columns):
 #   Column                                          Non-Null Count  Dtype
---  ------                                          --------------  -----
 0   OBJECTID                                        2994 non-null   int64
 1   Wat Break Incident ID                           2994 non-null   int64
 2   Incident date                                   2994 non-null   str
 3   Type of Asset Broken                            2994 non-null   str
 4   Does the road need to be closed?                540 non-null    str
 5   Does the sidewalk need to be closed?            537 non-null    str
 6   Estimated Hours for Repair                      538 non-null    str
 7   Estimated Number of Units Impacted              525 non-null    str
 8   CW Service Request Number                       25 non-null     float64
 9   Current status of the break                     2994 non-null   str
 10  Status last updated date                        2843 non-null   str
 11  CW Workorder #                                  1826 non-null   float64
 12  Date operations was returned to normal service  106 non-null    str
 13  Nature of Break                                 2682 non-null   str
 14  Apparent cause of break                         2558 non-null   str
 15  Repair Type                                     246 non-null    str
 16  Type of Planned Maintenance                     0 non-null      float64
 17  List Valves Closed                              3 non-null      str
 18  List Valves Opened                              2 non-null      float64
 19  List Hydrants Called Out                        48 non-null     str
 20  List Hydrants Called Back In                    36 non-null     str
 21  Categorization of the Break                     2693 non-null   str
 22  Road Segment ID                                 2994 non-null   int64
 23  Closest Civic Number                            2897 non-null   str
 24  Street                                          2979 non-null   str
 25  Related Asset ID                                2994 non-null   int64
 26  Related Asset Depth (m)                         15 non-null     float64
 27  Depth of Frost (m)                              82 non-null     float64
 28  Asset Size (cm)                                 2695 non-null   float64
 29  Year Asset Installed                            2691 non-null   float64
 30  Asset Material                                  2695 non-null   str
 31  Asset Exists                                    2994 non-null   str
 32  GLOBALID                                        2994 non-null   str
 33  UPDATE_BY                                       2447 non-null   str
 34  UPDATE_DATE                                     2447 non-null   str
 35  x                                               2994 non-null   float64
 36  y                                               2994 non-null   float64
dtypes: float64(10), int64(4), str(23)
memory usage: 865.6 KB

Kitchener Water Mains info:
<class 'pandas.DataFrame'>
RangeIndex: 16163 entries, 0 to 16162
Data columns (total 27 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   OBJECTID              16163 non-null  int64
 1   WATMAINID             16163 non-null  int64
 2   STATUS                16163 non-null  str
 3   PRESSURE_ZONE         16163 non-null  str
 4   ROADSEGMENTID         16163 non-null  int64
 5   MAP_LABEL             16163 non-null  str
 6   CATEGORY              16163 non-null  str
 7   PIPE_SIZE             16163 non-null  int64
 8   MATERIAL              16163 non-null  str
 9   LINED                 16163 non-null  str
 10  LINED_DATE            54 non-null     str
 11  LINED_MATERIAL        16163 non-null  str
 12  INSTALLATION_DATE     16163 non-null  str
 13  ACQUISITION           16163 non-null  str
 14  CONSULTANT            4566 non-null   str
 15  OWNERSHIP             16163 non-null  str
 16  BRIDGE_MAIN           16163 non-null  str
 17  BRIDGE_DETAILS        8 non-null      str
 18  CRITICALITY           16163 non-null  int64
 19  REL_CLEANING_AREA     16163 non-null  int64
 20  REL_CLEANING_SUBAREA  16163 non-null  str
 21  Undersized            16163 non-null  str
 22  Shallow Main          16163 non-null  str
 23  Condition Score       16163 non-null  float64
 24  OVERSIZED             16163 non-null  str
 25  CLEANED               16163 non-null  str
 26  Shape__Length         16163 non-null  float64
dtypes: float64(2), int64(6), str(19)
memory usage: 3.3 MB

### Check statistics for missing values

In [156]:

# print the count and percentage of missing values for each column

# Define constants
MISSING_COUNT = 'Missing Count'
MISSING_PERCENT = 'Missing %'
NON_NULL_COUNT = 'Non-Null Count'

# using the dataframe already loaded for Bozeman dataset
print("\n=== Bozeman Missing Values Analysis ===")
dfBozeman = bozemanDataFrame  
missing = pd.DataFrame({
    MISSING_COUNT: dfBozeman.isna().sum(),
    MISSING_PERCENT: (dfBozeman.isna().sum() / len(dfBozeman) * 100).round(2),
    NON_NULL_COUNT: dfBozeman.notna().sum()
})
print(missing)

# using the dataframe already loaded for Kitchener datasets
print("\n=== Kitchener Missing Values Analysis ===")
dfKWaterMainBreaks = kitchenerWaterMainBreaksDf
missing = pd.DataFrame({
    MISSING_COUNT: dfKWaterMainBreaks.isna().sum(),
    MISSING_PERCENT: (dfKWaterMainBreaks.isna().sum() / len(dfKWaterMainBreaks) * 100).round(2),
    NON_NULL_COUNT: dfKWaterMainBreaks.notna().sum()
})
print(missing)

# using the dataframe already loaded for Kitchener datasets
print("\n=== Kitchener Water Mains Missing Values Analysis ===")

dfKWatermains = kitchenerWaterMainsDf
missing = pd.DataFrame({
    MISSING_COUNT: dfKWatermains.isna().sum(),
    MISSING_PERCENT: (dfKWatermains.isna().sum() / len(dfKWatermains) * 100).round(2),
    NON_NULL_COUNT: dfKWatermains.notna().sum()
})
print(missing)

=== Bozeman Missing Values Analysis ===
                 Missing Count  Missing %  Non-Null Count
X                            0       0.00             158
Y                            0       0.00             158
OBJECTID_1                   0       0.00             158
Break_Date                   0       0.00             158
Address                      5       3.16             153
Pipe_Size                    1       0.63             157
Type_of_Leak                 0       0.00             158
Cost                         2       1.27             156
WOID                        36      22.78             122
FACID                        1       0.63             157
PIPE_INSTALL_DA              3       1.90             155
Detected                     0       0.00             158

=== Kitchener Missing Values Analysis ===
                                                Missing Count  Missing %  \
OBJECTID                                                    0       0.00
Wat Break Incident ID                                       0       0.00
Incident date                                               0       0.00
Type of Asset Broken                                        0       0.00
Does the road need to be closed?                         2454      81.96
Does the sidewalk need to be closed?                     2457      82.06
Estimated Hours for Repair                               2456      82.03
Estimated Number of Units Impacted                       2469      82.46
CW Service Request Number                                2969      99.16
Current status of the break                                 0       0.00
Status last updated date                                  151       5.04
CW Workorder #                                           1168      39.01
Date operations was returned to normal service           2888      96.46
Nature of Break                                           312      10.42
Apparent cause of break                                   436      14.56
Repair Type                                              2748      91.78
Type of Planned Maintenance                              2994     100.00
List Valves Closed                                       2991      99.90
List Valves Opened                                       2992      99.93
List Hydrants Called Out                                 2946      98.40
List Hydrants Called Back In                             2958      98.80
Categorization of the Break                               301      10.05
Road Segment ID                                             0       0.00
Closest Civic Number                                       97       3.24
Street                                                     15       0.50
Related Asset ID                                            0       0.00
Related Asset Depth (m)                                  2979      99.50
Depth of Frost (m)                                       2912      97.26
Asset Size (cm)                                           299       9.99
Year Asset Installed                                      303      10.12
Asset Material                                            299       9.99
Asset Exists                                                0       0.00
GLOBALID                                                    0       0.00
UPDATE_BY                                                 547      18.27
UPDATE_DATE                                               547      18.27
x                                                           0       0.00
y                                                           0       0.00

                                                Non-Null Count
OBJECTID                                                  2994
Wat Break Incident ID                                     2994
Incident date                                             2994
Type of Asset Broken                                      2994
Does the road need to be closed?                           540
Does the sidewalk need to be closed?                       537
Estimated Hours for Repair                                 538
Estimated Number of Units Impacted                         525
CW Service Request Number                                   25
Current status of the break                               2994
Status last updated date                                  2843
CW Workorder #                                            1826
Date operations was returned to normal service             106
Nature of Break                                           2682
Apparent cause of break                                   2558
Repair Type                                                246
Type of Planned Maintenance                                  0
List Valves Closed                                           3
List Valves Opened                                           2
List Hydrants Called Out                                    48
List Hydrants Called Back In                                36
Categorization of the Break                               2693
Road Segment ID                                           2994
Closest Civic Number                                      2897
Street                                                    2979
Related Asset ID                                          2994
Related Asset Depth (m)                                     15
Depth of Frost (m)                                          82
Asset Size (cm)                                           2695
Year Asset Installed                                      2691
Asset Material                                            2695
Asset Exists                                              2994
GLOBALID                                                  2994
UPDATE_BY                                                 2447
UPDATE_DATE                                               2447
x                                                         2994
y                                                         2994

=== Kitchener Water Mains Missing Values Analysis ===
                      Missing Count  Missing %  Non-Null Count
OBJECTID                          0       0.00           16163
WATMAINID                         0       0.00           16163
STATUS                            0       0.00           16163
PRESSURE_ZONE                     0       0.00           16163
ROADSEGMENTID                     0       0.00           16163
MAP_LABEL                         0       0.00           16163
CATEGORY                          0       0.00           16163
PIPE_SIZE                         0       0.00           16163
MATERIAL                          0       0.00           16163
LINED                             0       0.00           16163
LINED_DATE                    16109      99.67              54
LINED_MATERIAL                    0       0.00           16163
INSTALLATION_DATE                 0       0.00           16163
ACQUISITION                       0       0.00           16163
CONSULTANT                    11597      71.75            4566
OWNERSHIP                         0       0.00           16163
BRIDGE_MAIN                       0       0.00           16163
BRIDGE_DETAILS                16155      99.95               8
CRITICALITY                       0       0.00           16163
REL_CLEANING_AREA                 0       0.00           16163
REL_CLEANING_SUBAREA              0       0.00           16163
Undersized                        0       0.00           16163
Shallow Main                      0       0.00           16163
Condition Score                   0       0.00           16163
OVERSIZED                         0       0.00           16163
CLEANED                           0       0.00           16163
Shape__Length                     0       0.00           16163

### Deplicates check for the datasets

In [ ]:
#duplicate analysis 

# Assuming your dataframe is called df
print("=== Bozeman Duplicate Check ===")

# Total number of duplicate rows
total_duplicates = dfBozeman.duplicated().sum()
print(f"Total duplicate rows: {total_duplicates}")

# Percentage of duplicates
if len(dfBozeman) > 0:
    duplicate_pct = (total_duplicates / len(dfBozeman) * 100).round(2)
    print(f"Duplicate percentage: {duplicate_pct}%")


print("\n=== Kitchener Water Main Breaks Duplicate Check ===")

# Total number of duplicate rows
total_duplicates = dfKWaterMainBreaks.duplicated().sum()
print(f"Total duplicate rows: {total_duplicates}")  

# Percentage of duplicates
if len(dfKWaterMainBreaks) > 0:
    duplicate_pct = (total_duplicates / len(dfKWaterMainBreaks) * 100).round(2)
    print(f"Duplicate percentage: {duplicate_pct}%")

print("\n=== Kitchener Water Mains Duplicate Check ===")

# Total number of duplicate rows
total_duplicates = dfKWatermains.duplicated().sum()
print(f"Total duplicate rows: {total_duplicates}")

# Percentage of duplicates
if len(dfKWatermains) > 0:
    duplicate_pct = (total_duplicates / len(dfKWatermains) * 100).round(2)
    print(f"Duplicate percentage: {duplicate_pct}%")

=== Bozeman Duplicate Check ===
Total duplicate rows: 0
Duplicate percentage: 0.0%

=== Kitchener Water Main Breaks Duplicate Check ===
Total duplicate rows: 0
Duplicate percentage: 0.0%

=== Kitchener Water Mains Duplicate Check ===
Total duplicate rows: 0
Duplicate percentage: 0.0%

### Data cleaning

In [158]:
# Data Cleaning: Drop rows with missing data in critical columns for Bozeman dataset

def clean_data(df):
    # Drop rows with missing data in columns: 'FACID', 'WOID' and 4 other columns
    df = df.dropna(subset=['FACID', 'WOID', 'Cost', 'PIPE_INSTALL_DA', 'Pipe_Size', 'Address'])
    return df
df_clean_bozeman = clean_data(dfBozeman.copy())

# Data Cleaning: Convert 'Break_Date' to datetime and remove timezone information
df_clean_bozeman['Break_Date'] = pd.to_datetime(df_clean_bozeman['Break_Date'], errors='coerce')
df_clean_bozeman['Break_Date'] = df_clean_bozeman['Break_Date'].dt.tz_localize(None)

# Data Cleaning: Convert 'PIPE_INSTALL_DA' to integer and create a new column 'Install_Year', then drop the original 'PIPE_INSTALL_DA' column
df_clean_bozeman['Install_Year'] = df_clean_bozeman['PIPE_INSTALL_DA'].astype(int)
df_clean_bozeman.drop(columns=['PIPE_INSTALL_DA'], inplace=True)

# Data Cleaning: Drop columns with low relevance for Bozeman dataset
df_clean_bozeman = df_clean_bozeman.drop(columns=['X', 'Y', 'WOID', 'FACID'])

# Display the cleaned Bozeman dataset
df_clean_bozeman.head(10)

,OBJECTID_1,Break_Date,Address,Pipe_Size,Type_of_Leak,Cost,Detected,Install_Year
0,1,2013-01-28,431 N 4TH,6.0,Corrosion,3273.33,No,1948
1,2,2012-08-11,1126 N 7TH (KMART),8.0,Longitudinal Break,286.10,No,1974
4,5,2009-05-28,S WALLACE AVE& E OLIVE ST,6.0,Full Circle Break,2222.83,No,1924
8,9,2011-05-18,Peach St. between Bozeman and Black,6.0,Leaking Joint,2229.56,No,1929
9,10,2008-12-04,1922 W BABCOCK,10.0,Longitudinal Break,7483.67,No,1971
13,14,2014-07-23,Peach & Grand,6.0,Blow-out,3230.01,No,1903
14,15,2011-05-10,PEAR ST BOSTER SOUTH OF,16.0,Leaking Joint,3271.98,No,1992
15,16,2014-06-25,N Rouse near Bryant,4.0,Full Circle Break,3837.12,No,1950
16,17,2012-11-14,1207 E CURTISS,6.0,Full Circle Break,2565.40,No,1971
18,19,2008-12-19,300 BLOCK NORTH 16TH,6.0,Full Circle Break,1882.14,No,1966

In [159]:
# Data Cleaning: Drop rows with missing data in critical columns for Kitchener Water Main Breaks dataset
def clean_data(df):
    # Drop columns: with high percentage of missing values and low relevance for analysis
    df = df.drop(columns=['Does the road need to be closed?', 'Does the sidewalk need to be closed?', 'Estimated Hours for Repair', 'Estimated Number of Units Impacted', 'CW Service Request Number', 'Date operations was returned to normal service', 'Repair Type', 'Type of Planned Maintenance', 'List Valves Closed', 'List Valves Opened', 'List Hydrants Called Out', 'List Hydrants Called Back In', 'Related Asset Depth (m)', 'Depth of Frost (m)','GLOBALID','x','y'])
    
    # Drop rows with missing data in columns: 'UPDATE_DATE', 'UPDATE_BY' and 10 other columns
    df = df.dropna(subset=['UPDATE_DATE', 'UPDATE_BY', 'Asset Material', 'Year Asset Installed', 'Asset Size (cm)', 'Street', 'Closest Civic Number', 'Categorization of the Break', 'Apparent cause of break', 'Nature of Break', 'CW Workorder #', 'Status last updated date'])
    return df

df_clean_kitchenerWaterMainBreaks = clean_data(dfKWaterMainBreaks.copy())

kitchener_date_columns = ['Incident date', 'Status last updated date', 'UPDATE_DATE']

# Convert date columns to datetime and remove timezone information
for col in kitchener_date_columns:
    if col in df_clean_kitchenerWaterMainBreaks.columns:

        # Use format='mixed' to suppress the warning and improve performance
        # This allows pandas to infer the date format for each entry, which is more efficient than trying multiple formats
        df_clean_kitchenerWaterMainBreaks[col] = pd.to_datetime(
            df_clean_kitchenerWaterMainBreaks[col], 
            format='mixed',      
            errors='coerce'
        ).dt.tz_localize(None).dt.normalize()  # Normalize to remove time component
        
# Display the cleaned Kitchener Water Main Breaks dataset      
#print(df_clean_kitchenerWaterMainBreaks.head(10).to_string())
df_clean_kitchenerWaterMainBreaks.head(10)

,OBJECTID,Wat Break Incident ID,Incident date,Type of Asset Broken,Current status of the break,Status last updated date,CW Workorder #,Nature of Break,Apparent cause of break,Categorization of the Break,Road Segment ID,Closest Civic Number,Street,Related Asset ID,Asset Size (cm),Year Asset Installed,Asset Material,Asset Exists,UPDATE_BY,UPDATE_DATE
0,1,2252,2017-12-01,MAIN,REPAIR COMPLETED,2017-12-02,177898.0,CORROSION AND FITTING/JOINT,AGE,CATEGORY 2,6961,125,LANCASTER ST W,134292,450.0,1937.0,CI,Y,GIS_DATA,2018-10-03
2,7875,1325,2006-09-06,SERVICE,REPAIR COMPLETED,2011-12-15,162230.0,UNKNOWN,OTHER,CATEGORY 1,13207,47,WREN CRES,4099987,25.0,1967.0,XXX,Y,DAVIDV,2011-12-15
13,7886,1407,2009-10-27,SERVICE,REPAIR COMPLETED,2011-12-15,15782.0,UNKNOWN,OTHER,CATEGORY 1,1249,136,GLASGOW ST,4736474,300.0,2017.0,PVC,N,DAVIDV,2011-12-15
15,7888,1323,2006-05-06,SERVICE,REPAIR COMPLETED,2011-12-15,156348.0,UNKNOWN,OTHER,CATEGORY 1,600416,385,FAIRWAY RD S,4096289,50.0,1990.0,XXX,Y,DAVIDV,2011-12-15
32,8018,1130,2007-04-23,MAIN,REPAIR COMPLETED,2011-12-15,172723.0,UNKNOWN,OTHER,CATEGORY 1,21220,392,WESTHEIGHTS DR,42130,300.0,1974.0,DI,Y,DAVIDV,2011-12-15
41,8027,1341,2009-01-17,MAIN,REPAIR COMPLETED,2011-12-15,3475.0,UNKNOWN,OTHER,CATEGORY 1,23174,93,KINGSTON CRES,22200,150.0,1966.0,CI,Y,DAVIDV,2021-10-25
45,8031,1834,2013-03-21,MAIN,REPAIR COMPLETED,2014-02-07,79095.0,CIRCUMFERENTIAL,COMBINATION,CATEGORY 1,10141,26,EDMUND RD,11480,150.0,1949.0,CI,Y,DAVIDV,2014-02-07
46,8032,1835,2013-03-21,MAIN,REPAIR COMPLETED,2014-02-07,79063.0,CIRCUMFERENTIAL,AGE,CATEGORY 1,15895,122,LOIS ST,33410,150.0,1958.0,CI,Y,DAVIDV,2014-02-07
47,8033,1836,2013-03-19,MAIN,REPAIR COMPLETED,2014-02-07,78943.0,CORROSION AND CIRCUMFERENTIAL,AGE,CATEGORY 1,23175,124,QUEENSTON DR,31930,150.0,1966.0,DI,Y,DAVIDV,2014-02-07
48,8034,1838,2013-03-10,MAIN,REPAIR COMPLETED,2014-02-07,78617.0,CIRCUMFERENTIAL,AGE,CATEGORY 1,10044,374,PROSPECT AVE,31180,150.0,1954.0,CI,Y,DAVIDV,2014-02-07

In [160]:
# Data Cleaning: Drop columns with low relevance for Kitchener Water Mains dataset
def clean_data(df):
    # Drop columns: 'LINED_DATE', 'CONSULTANT', 'BRIDGE_DETAILS'
    df = df.drop(columns=['LINED_DATE', 'CONSULTANT', 'BRIDGE_DETAILS'])
    return df

df_clean_kitchenerWaterMains = clean_data(dfKWatermains.copy())
df_clean_kitchenerWaterMains.head(10)

,OBJECTID,WATMAINID,STATUS,PRESSURE_ZONE,ROADSEGMENTID,MAP_LABEL,CATEGORY,PIPE_SIZE,MATERIAL,LINED,...,BRIDGE_MAIN,CRITICALITY,REL_CLEANING_AREA,REL_CLEANING_SUBAREA,Undersized,Shallow Main,Condition Score,OVERSIZED,CLEANED,Shape__Length
0,77753,10080,ACTIVE,KIT 6,5457,34.2m 450mm DI,TREATED,450,DI,NO,...,N,6,6,8,N,N,8.50,N,N,34.210563
1,77754,76299,ACTIVE,KIT 4,6390,.4m 300mm DI,TREATED,300,DI,NO,...,N,7,1,4,N,N,8.50,N,N,0.355118
2,77755,10110,ACTIVE,KIT 6,5393,67.9m 450mm DI,TREATED,450,DI,NO,...,N,7,6,8,N,N,6.10,N,Y,67.852910
3,77756,82566,ACTIVE,KIT 6,5393,7m 450mm DI,TREATED,450,DI,NO,...,N,6,6,8,N,N,4.58,N,Y,7.039328
4,77757,82568,ACTIVE,KIT 6,5394,15m 450mm DI,TREATED,450,DI,NO,...,N,6,6,8,N,N,8.50,N,Y,14.956131
5,77758,10090,ACTIVE,KIT 6,5402,38.5m 450mm DI,TREATED,450,DI,NO,...,N,6,6,8,N,N,8.50,N,Y,38.526891
6,77759,82570,ACTIVE,KIT 6,5456,12.5m 450mm DI,TREATED,450,DI,NO,...,N,6,6,7,N,N,8.50,N,N,12.451964
7,77760,10030,ACTIVE,KIT 6,21108,125m 450mm DI,TREATED,450,DI,NO,...,N,7,6,7,N,N,8.50,N,N,124.970065
8,77761,10100,ACTIVE,KIT 6,5396,55.7m 450mm DI,TREATED,450,DI,NO,...,N,6,6,8,N,N,8.50,N,Y,55.671581
9,77762,81620,ACTIVE,KIT 2W,102861,63.9m 300mm PVC,TREATED,300,PVC,NO,...,N,0,5,46,N,N,9.35,N,N,63.948585

In [161]:
# Display the cleaned datasets

print("\n=== Cleaned Bozeman Dataset ===")
print(df_clean_bozeman.head(10).to_string())

print("\n=== Cleaned Kitchener Water Main Breaks Dataset ===")
print(df_clean_kitchenerWaterMainBreaks.head(10).to_string())

print("\n=== Cleaned Kitchener Water Mains Dataset ===")
print(df_clean_kitchenerWaterMains.head(10).to_string())

=== Cleaned Bozeman Dataset ===
    OBJECTID_1 Break_Date                              Address  Pipe_Size        Type_of_Leak     Cost Detected  Install_Year
0            1 2013-01-28                            431 N 4TH        6.0           Corrosion  3273.33       No          1948
1            2 2012-08-11                   1126 N 7TH (KMART)        8.0  Longitudinal Break   286.10       No          1974
4            5 2009-05-28            S WALLACE AVE& E OLIVE ST        6.0   Full Circle Break  2222.83       No          1924
8            9 2011-05-18  Peach St. between Bozeman and Black        6.0       Leaking Joint  2229.56       No          1929
9           10 2008-12-04                       1922 W BABCOCK       10.0  Longitudinal Break  7483.67       No          1971
13          14 2014-07-23                        Peach & Grand        6.0            Blow-out  3230.01       No          1903
14          15 2011-05-10              PEAR ST BOSTER SOUTH OF       16.0       Leaking Joint  3271.98       No          1992
15          16 2014-06-25                  N Rouse near Bryant        4.0   Full Circle Break  3837.12       No          1950
16          17 2012-11-14                       1207 E CURTISS        6.0   Full Circle Break  2565.40       No          1971
18          19 2008-12-19                 300 BLOCK NORTH 16TH        6.0   Full Circle Break  1882.14       No          1966

=== Cleaned Kitchener Water Main Breaks Dataset ===
    OBJECTID  Wat Break Incident ID Incident date Type of Asset Broken Current status of the break Status last updated date  CW Workorder #                Nature of Break Apparent cause of break Categorization of the Break  Road Segment ID Closest Civic Number          Street  Related Asset ID  Asset Size (cm)  Year Asset Installed Asset Material Asset Exists UPDATE_BY UPDATE_DATE
0          1                   2252    2017-12-01                 MAIN            REPAIR COMPLETED               2017-12-02        177898.0    CORROSION AND FITTING/JOINT                     AGE                  CATEGORY 2             6961                  125  LANCASTER ST W            134292            450.0                1937.0             CI            Y  GIS_DATA  2018-10-03
2       7875                   1325    2006-09-06              SERVICE            REPAIR COMPLETED               2011-12-15        162230.0                        UNKNOWN                   OTHER                  CATEGORY 1            13207                   47       WREN CRES           4099987             25.0                1967.0            XXX            Y    DAVIDV  2011-12-15
13      7886                   1407    2009-10-27              SERVICE            REPAIR COMPLETED               2011-12-15         15782.0                        UNKNOWN                   OTHER                  CATEGORY 1             1249                  136      GLASGOW ST           4736474            300.0                2017.0            PVC            N    DAVIDV  2011-12-15
15      7888                   1323    2006-05-06              SERVICE            REPAIR COMPLETED               2011-12-15        156348.0                        UNKNOWN                   OTHER                  CATEGORY 1           600416                  385    FAIRWAY RD S           4096289             50.0                1990.0            XXX            Y    DAVIDV  2011-12-15
32      8018                   1130    2007-04-23                 MAIN            REPAIR COMPLETED               2011-12-15        172723.0                        UNKNOWN                   OTHER                  CATEGORY 1            21220                  392  WESTHEIGHTS DR             42130            300.0                1974.0             DI            Y    DAVIDV  2011-12-15
41      8027                   1341    2009-01-17                 MAIN            REPAIR COMPLETED               2011-12-15          3475.0                        UNKNOWN                   OTHER                  CATEGORY 1            23174                   93   KINGSTON CRES             22200            150.0                1966.0             CI            Y    DAVIDV  2021-10-25
45      8031                   1834    2013-03-21                 MAIN            REPAIR COMPLETED               2014-02-07         79095.0                CIRCUMFERENTIAL             COMBINATION                  CATEGORY 1            10141                   26       EDMUND RD             11480            150.0                1949.0             CI            Y    DAVIDV  2014-02-07
46      8032                   1835    2013-03-21                 MAIN            REPAIR COMPLETED               2014-02-07         79063.0                CIRCUMFERENTIAL                     AGE                  CATEGORY 1            15895                  122         LOIS ST             33410            150.0                1958.0             CI            Y    DAVIDV  2014-02-07
47      8033                   1836    2013-03-19                 MAIN            REPAIR COMPLETED               2014-02-07         78943.0  CORROSION AND CIRCUMFERENTIAL                     AGE                  CATEGORY 1            23175                  124    QUEENSTON DR             31930            150.0                1966.0             DI            Y    DAVIDV  2014-02-07
48      8034                   1838    2013-03-10                 MAIN            REPAIR COMPLETED               2014-02-07         78617.0                CIRCUMFERENTIAL                     AGE                  CATEGORY 1            10044                  374    PROSPECT AVE             31180            150.0                1954.0             CI            Y    DAVIDV  2014-02-07

=== Cleaned Kitchener Water Mains Dataset ===
   OBJECTID  WATMAINID  STATUS PRESSURE_ZONE  ROADSEGMENTID         MAP_LABEL CATEGORY  PIPE_SIZE MATERIAL LINED LINED_MATERIAL     INSTALLATION_DATE ACQUISITION             OWNERSHIP BRIDGE_MAIN  CRITICALITY  REL_CLEANING_AREA REL_CLEANING_SUBAREA Undersized Shallow Main  Condition Score OVERSIZED CLEANED  Shape__Length
0     77753      10080  ACTIVE         KIT 6           5457   34.2m 450mm  DI  TREATED        450       DI    NO           NONE  1/1/1979 12:00:00 AM     DONATED  DUAL CITY AND REGION           N            6                  6                    8          N            N             8.50         N       N      34.210563
1     77754      76299  ACTIVE         KIT 4           6390     .4m 300mm  DI  TREATED        300       DI    NO           NONE  7/1/1968 12:00:00 AM   PURCHASED                REGION           N            7                  1                    4          N            N             8.50         N       N       0.355118
2     77755      10110  ACTIVE         KIT 6           5393   67.9m 450mm  DI  TREATED        450       DI    NO           NONE  1/1/1979 12:00:00 AM     DONATED  DUAL CITY AND REGION           N            7                  6                    8          N            N             6.10         N       Y      67.852910
3     77756      82566  ACTIVE         KIT 6           5393      7m 450mm  DI  TREATED        450       DI    NO           NONE  1/1/1979 12:00:00 AM     DONATED  DUAL CITY AND REGION           N            6                  6                    8          N            N             4.58         N       Y       7.039328
4     77757      82568  ACTIVE         KIT 6           5394     15m 450mm  DI  TREATED        450       DI    NO           NONE  1/1/1979 12:00:00 AM     DONATED  DUAL CITY AND REGION           N            6                  6                    8          N            N             8.50         N       Y      14.956131
5     77758      10090  ACTIVE         KIT 6           5402   38.5m 450mm  DI  TREATED        450       DI    NO           NONE  1/1/1979 12:00:00 AM     DONATED  DUAL CITY AND REGION           N            6                  6                    8          N            N             8.50         N       Y      38.526891
6     77759      82570  ACTIVE         KIT 6           5456   12.5m 450mm  DI  TREATED        450       DI    NO           NONE  1/1/1979 12:00:00 AM     DONATED  DUAL CITY AND REGION           N            6                  6                    7          N            N             8.50         N       N      12.451964
7     77760      10030  ACTIVE         KIT 6          21108    125m 450mm  DI  TREATED        450       DI    NO           NONE  1/1/1979 12:00:00 AM     DONATED  DUAL CITY AND REGION           N            7                  6                    7          N            N             8.50         N       N     124.970065
8     77761      10100  ACTIVE         KIT 6           5396   55.7m 450mm  DI  TREATED        450       DI    NO           NONE  1/1/1979 12:00:00 AM     DONATED  DUAL CITY AND REGION           N            6                  6                    8          N            N             8.50         N       Y      55.671581
9     77762      81620  ACTIVE        KIT 2W         102861  63.9m 300mm  PVC  TREATED        300      PVC    NO           NONE  1/6/2015 12:00:00 AM   PURCHASED             KITCHENER           N            0                  5                   46          N            N             9.35         N       N      63.948585

### Preprocessing will be the next step