# 02_crash_data_import.ipynb

## Project Title: Traffic Accident Risk Prediction (TARP)

**Unit:** SIT782  
**Prepared by:** Khalid  
**Project Team:** Suba (225094537), Burhan (224802775), Khalid (224696667)  
**Task:** Import and explore the Victorian Road Crash Data (Week 1 of 8)

### Objectives
- Download and load the Victorian Road Crash dataset
- Explore the dataset structure
- Inspect columns and basic data quality
- Identify useful variables for the capstone project
- Create a starter data dictionary

## 1. Dataset source

Official dataset: **Victoria road crash data** from the Victorian Government open data portal.

For this notebook, we use the **accident.csv** table, which contains core accident-level records such as date, time, severity, crash type, road geometry, and speed zone.

> Note: The broader dataset is split across multiple related tables. The portal notes that the crash data is updated monthly with a 7‑month lag, and that location detail can be linked through node/location tables when needed later for hotspot mapping.

In [47]:
import pandas as pd
import numpy as np
from pathlib import Path

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 100)

## 2. Define file path

The project structure:

```text
Traffic_Accident_Prediction/
├── data/
│   └── raw/
│       └── accident.csv
├── notebooks/
│   └── 02_crash_data_import.ipynb
└── outputs/
```

In [66]:
# let's make sure our working directory is up-to-date to avoid any issues accessing different data sets 

import os

os.chdir(r"D:\Git\SIT782\TARP01\MOP-Code\Playground\KhalidT12026\Traffic_Accident_Prediction")

## 3. Load the crash dataset

In [67]:
# Now we can load the data set using local file inside the repository

crash_df = pd.read_csv("data/raw/accident.csv")

print("Dataset loaded successfully.")
print("Shape:", df.shape)
crash_df.head()

Dataset loaded successfully.
Shape: (194437, 52)

,ACCIDENT_NO,ACCIDENT_DATE,ACCIDENT_TIME,ACCIDENT_TYPE,DAY_OF_WEEK,DCA_CODE,DCA_CODE_DESCRIPTION,LIGHT_CONDITION,POLICE_ATTEND,ROAD_GEOMETRY,SEVERITY,SPEED_ZONE,RUN_OFFROAD,ROAD_NAME,ROAD_TYPE,ROAD_ROUTE_1,LGA_NAME,DTP_REGION,LATITUDE,LONGITUDE,VICGRID_X,VICGRID_Y,TOTAL_PERSONS,INJ_OR_FATAL,FATALITY,SERIOUSINJURY,OTHERINJURY,NONINJURED,MALES,FEMALES,BICYCLIST,PASSENGER,DRIVER,PEDESTRIAN,PILLION,MOTORCYCLIST,UNKNOWN,PED_CYCLIST_5_12,PED_CYCLIST_13_18,OLD_PED_65_AND_OVER,OLD_DRIVER_75_AND_OVER,YOUNG_DRIVER_18_25,NO_OF_VEHICLES,HEAVYVEHICLE,PASSENGERVEHICLE,MOTORCYCLE,PT_VEHICLE,DEG_URBAN_NAME,SRNS,RMA,DIVIDED,STAT_DIV_NAME
0,T20230013207,2023-06-06,22:14:00,Collision with vehicle,Tuesday,140,U TURN,Dark Street lights on,Yes,Not at intersection,Serious injury accident,50 km/hr,No,CUMBERLAND,ROAD,5749.0,MORELAND,INNER METRO,-37.723442,144.93985,2494697.067,2419717.845,2,2,0,1,1,0,2,0,0,0,2,0,0,0,0,0,0,0,0,0,2.0,0.0,2.0,0.0,0.0,MELB_URBAN,NaN,Arterial Other,Undivided,Metro
1,T20240014902,2024-04-19,02:10:00,Collision with vehicle,Friday,140,U TURN,Dark Street lights on,Yes,Not at intersection,Other injury accident,40 km/hr,No,CHAPEL,STREET,9999.0,STONNINGTON,INNER METRO,-37.850610,144.99355,2499432.181,2405605.392,3,1,0,0,1,2,2,1,0,1,2,0,0,0,0,0,0,0,0,0,2.0,0.0,2.0,0.0,0.0,MELB_URBAN,NaN,Local Road,Undivided,Metro
2,T20160009452,2016-04-30,23:50:00,Collision with vehicle,Saturday,120,HEAD ON (NOT OVERTAKING),Dark No street lights,Yes,Not at intersection,Serious injury accident,100 km/hr,No,BRANDY CREEK,ROAD,5532.0,BAW BAW,GIPPSLAND,-38.111640,145.92566,2581181.074,2376237.515,3,3,0,1,2,0,1,2,0,1,2,0,0,0,0,0,0,0,0,0,2.0,0.0,2.0,0.0,0.0,RURAL_VICTORIA,C,Arterial Other,Undivided,Country
3,T20230001223,2023-01-17,15:56:00,Collision with vehicle,Tuesday,113,RIGHT NEAR (INTERSECTIONS ONLY),Day,Yes,Private property,Serious injury accident,100 km/hr,No,MIDLAND,HIGHWAY,2590.0,SHEPPARTON,HUME,-36.409386,145.25609,2522967.147,2565502.025,4,1,0,1,0,3,0,4,0,2,2,0,0,0,0,0,0,0,0,1,2.0,0.0,2.0,0.0,0.0,RURAL_VICTORIA,A,Arterial Highway,Undivided,Country
4,T20220001324,2022-01-21,22:45:00,Fall from or in moving vehicle,Friday,190,FELL IN/FROM VEHICLE,Dark Street lights on,Yes,Cross intersection,Serious injury accident,50 km/hr,No,URQUHART,STREET,9999.0,MOUNT ALEXANDER,LODDON MALLEE,-37.065030,144.22215,2430833.236,2492501.459,4,1,0,1,0,3,4,0,0,3,1,0,0,0,0,0,0,0,0,0,1.0,0.0,0.0,0.0,0.0,TOWNS,NaN,Local Road,Undivided,Country

## 4. Explore structure and columns

In [68]:
# Now we will explore to understand the available data and it's type. 

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 194437 entries, 0 to 194436
Data columns (total 52 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   ACCIDENT_NO             194437 non-null  object
 1   ACCIDENT_DATE           194437 non-null  object
 2   ACCIDENT_TIME           194437 non-null  object
 3   ACCIDENT_TYPE           194437 non-null  object
 4   DAY_OF_WEEK             194437 non-null  object
 5   DCA_CODE                194437 non-null  int64
 6   DCA_CODE_DESCRIPTION    194437 non-null  object
 7   LIGHT_CONDITION         194437 non-null  object
 8   POLICE_ATTEND           194437 non-null  object
 9   ROAD_GEOMETRY           194437 non-null  object
 10  SEVERITY                194437 non-null  object
 11  SPEED_ZONE              194437 non-null  object
 12  RUN_OFFROAD             194437 non-null  object
 13  ROAD_NAME               194179 non-null  object
 14  ROAD_TYPE               191814 non-null  object
 15  ROAD_ROUTE_1            194352 non-null  float64
 16  LGA_NAME                194347 non-null  object
 17  DTP_REGION              194352 non-null  object
 18  LATITUDE                194352 non-null  float64
 19  LONGITUDE               194352 non-null  float64
 20  VICGRID_X               194352 non-null  float64
 21  VICGRID_Y               194352 non-null  float64
 22  TOTAL_PERSONS           194437 non-null  int64
 23  INJ_OR_FATAL            194437 non-null  int64
 24  FATALITY                194437 non-null  int64
 25  SERIOUSINJURY           194437 non-null  int64
 26  OTHERINJURY             194437 non-null  int64
 27  NONINJURED              194437 non-null  int64
 28  MALES                   194437 non-null  int64
 29  FEMALES                 194437 non-null  int64
 30  BICYCLIST               194437 non-null  int64
 31  PASSENGER               194437 non-null  int64
 32  DRIVER                  194437 non-null  int64
 33  PEDESTRIAN              194437 non-null  int64
 34  PILLION                 194437 non-null  int64
 35  MOTORCYCLIST            194437 non-null  int64
 36  UNKNOWN                 194437 non-null  int64
 37  PED_CYCLIST_5_12        194437 non-null  int64
 38  PED_CYCLIST_13_18       194437 non-null  int64
 39  OLD_PED_65_AND_OVER     194437 non-null  int64
 40  OLD_DRIVER_75_AND_OVER  194437 non-null  int64
 41  YOUNG_DRIVER_18_25      194437 non-null  int64
 42  NO_OF_VEHICLES          194428 non-null  float64
 43  HEAVYVEHICLE            194428 non-null  float64
 44  PASSENGERVEHICLE        194428 non-null  float64
 45  MOTORCYCLE              194428 non-null  float64
 46  PT_VEHICLE              194428 non-null  float64
 47  DEG_URBAN_NAME          193447 non-null  object
 48  SRNS                    57351 non-null   object
 49  RMA                     185674 non-null  object
 50  DIVIDED                 185674 non-null  object
 51  STAT_DIV_NAME           193426 non-null  object
dtypes: float64(10), int64(21), object(21)
memory usage: 77.1+ MB

In [52]:
columns_df = pd.DataFrame({
    "column_name": df.columns,
    "data_type": [str(df[col].dtype) for col in df.columns]
})
columns_df

               column_name data_type
0              ACCIDENT_NO    object
1            ACCIDENT_DATE    object
2            ACCIDENT_TIME    object
3            ACCIDENT_TYPE    object
4              DAY_OF_WEEK    object
5                 DCA_CODE     int64
6     DCA_CODE_DESCRIPTION    object
7          LIGHT_CONDITION    object
8            POLICE_ATTEND    object
9            ROAD_GEOMETRY    object
10                SEVERITY    object
11              SPEED_ZONE    object
12             RUN_OFFROAD    object
13               ROAD_NAME    object
14               ROAD_TYPE    object
15            ROAD_ROUTE_1   float64
16                LGA_NAME    object
17              DTP_REGION    object
18                LATITUDE   float64
19               LONGITUDE   float64
20               VICGRID_X   float64
21               VICGRID_Y   float64
22           TOTAL_PERSONS     int64
23            INJ_OR_FATAL     int64
24                FATALITY     int64
25           SERIOUSINJURY     int64
26             OTHERINJURY     int64
27              NONINJURED     int64
28                   MALES     int64
29                 FEMALES     int64
30               BICYCLIST     int64
31               PASSENGER     int64
32                  DRIVER     int64
33              PEDESTRIAN     int64
34                 PILLION     int64
35            MOTORCYCLIST     int64
36                 UNKNOWN     int64
37        PED_CYCLIST_5_12     int64
38       PED_CYCLIST_13_18     int64
39     OLD_PED_65_AND_OVER     int64
40  OLD_DRIVER_75_AND_OVER     int64
41      YOUNG_DRIVER_18_25     int64
42          NO_OF_VEHICLES   float64
43            HEAVYVEHICLE   float64
44        PASSENGERVEHICLE   float64
45              MOTORCYCLE   float64
46              PT_VEHICLE   float64
47          DEG_URBAN_NAME    object
48                    SRNS    object
49                     RMA    object
50                 DIVIDED    object
51           STAT_DIV_NAME    object

## 5. Basic profiling

This section checks:
- missing values
- unique values
- sample ranges / categories

In [53]:
profile_df = pd.DataFrame({
    "column_name": df.columns,
    "data_type": [str(df[col].dtype) for col in df.columns],
    "non_null_count": [df[col].notna().sum() for col in df.columns],
    "missing_count": [df[col].isna().sum() for col in df.columns],
    "missing_pct": [round(df[col].isna().mean() * 100, 2) for col in df.columns],
    "unique_values": [df[col].nunique(dropna=True) for col in df.columns]
})

profile_df.sort_values(by="missing_pct", ascending=False)

,column_name,data_type,non_null_count,missing_count,missing_pct,unique_values
48,SRNS,object,57351,137086,70.50,4
50,DIVIDED,object,185674,8763,4.51,2
49,RMA,object,185674,8763,4.51,6
14,ROAD_TYPE,object,191814,2623,1.35,80
51,STAT_DIV_NAME,object,193426,1011,0.52,2
47,DEG_URBAN_NAME,object,193447,990,0.51,7
13,ROAD_NAME,object,194179,258,0.13,14360
16,LGA_NAME,object,194347,90,0.05,87
21,VICGRID_Y,float64,194352,85,0.04,139345
20,VICGRID_X,float64,194352,85,0.04,139354
19,LONGITUDE,float64,194352,85,0.04,77892
18,LATITUDE,float64,194352,85,0.04,104633
17,DTP_REGION,object,194352,85,0.04,8
15,ROAD_ROUTE_1,float64,194352,85,0.04,1495
40,OLD_DRIVER_75_AND_OVER,int64,194437,0,0.00,4
31,PASSENGER,int64,194437,0,0.00,41
41,YOUNG_DRIVER_18_25,int64,194437,0,0.00,6
42,NO_OF_VEHICLES,float64,194428,9,0.00,16
43,HEAVYVEHICLE,float64,194428,9,0.00,5
44,PASSENGERVEHICLE,float64,194428,9,0.00,16
45,MOTORCYCLE,float64,194428,9,0.00,9
46,PT_VEHICLE,float64,194428,9,0.00,3
39,OLD_PED_65_AND_OVER,int64,194437,0,0.00,4
38,PED_CYCLIST_13_18,int64,194437,0,0.00,5
37,PED_CYCLIST_5_12,int64,194437,0,0.00,6
36,UNKNOWN,int64,194437,0,0.00,24
35,MOTORCYCLIST,int64,194437,0,0.00,9
34,PILLION,int64,194437,0,0.00,3
33,PEDESTRIAN,int64,194437,0,0.00,10
32,DRIVER,int64,194437,0,0.00,16
0,ACCIDENT_NO,object,194437,0,0.00,194437
30,BICYCLIST,int64,194437,0,0.00,9
10,SEVERITY,object,194437,0,0.00,4
2,ACCIDENT_TIME,object,194437,0,0.00,1460
3,ACCIDENT_TYPE,object,194437,0,0.00,9
4,DAY_OF_WEEK,object,194437,0,0.00,7
5,DCA_CODE,int64,194437,0,0.00,81
6,DCA_CODE_DESCRIPTION,object,194437,0,0.00,81
7,LIGHT_CONDITION,object,194437,0,0.00,7
8,POLICE_ATTEND,object,194437,0,0.00,3
9,ROAD_GEOMETRY,object,194437,0,0.00,9
11,SPEED_ZONE,object,194437,0,0.00,13
29,FEMALES,int64,194437,0,0.00,30
12,RUN_OFFROAD,object,194437,0,0.00,2
22,TOTAL_PERSONS,int64,194437,0,0.00,45
23,INJ_OR_FATAL,int64,194437,0,0.00,26
24,FATALITY,int64,194437,0,0.00,6
25,SERIOUSINJURY,int64,194437,0,0.00,12
1,ACCIDENT_DATE,object,194437,0,0.00,4961
27,NONINJURED,int64,194437,0,0.00,40
28,MALES,int64,194437,0,0.00,26
26,OTHERINJURY,int64,194437,0,0.00,23

In [54]:
print("Date range:", df["ACCIDENT_DATE"].min(), "to", df["ACCIDENT_DATE"].max())
print("Unique accident records:", df["ACCIDENT_NO"].nunique())
print("Duplicate ACCIDENT_NO:", df["ACCIDENT_NO"].duplicated().sum())

Date range: 1/01/2012 to 9/12/2024
Unique accident records: 194437
Duplicate ACCIDENT_NO: 0

In [55]:
crash_df.describe(include='object')

,ACCIDENT_NO,ACCIDENT_DATE,ACCIDENT_TIME,ACCIDENT_TYPE,DAY_OF_WEEK,DCA_CODE_DESCRIPTION,LIGHT_CONDITION,POLICE_ATTEND,ROAD_GEOMETRY,SEVERITY,SPEED_ZONE,RUN_OFFROAD,ROAD_NAME,ROAD_TYPE,LGA_NAME,DTP_REGION,DEG_URBAN_NAME,SRNS,RMA,DIVIDED,STAT_DIV_NAME
count,194437,194437,194437,194437,194437,194437,194437,194437,194437,194437,194437,194437,194179,191814,194347,194352,193447,57351,185674,185674,193426
unique,194437,4961,1505,9,7,81,7,3,9,4,13,2,14360,80,87,8,7,4,6,2,2
top,T20230013207,2015-04-17,16:00:00,Collision with vehicle,Friday,REAR END(VEHICLES IN SAME LANE),Day,Yes,Not at intersection,Other injury accident,60 km/hr,No,PRINCES,ROAD,MELBOURNE,INNER METRO,MELB_URBAN,C,Arterial Other,Undivided,Metro
freq,1,80,2783,126486,30627,35197,130255,143315,100794,121251,63513,160674,4974,97838,10127,77003,121519,25215,70506,119363,138403

In [56]:
crash_df.isnull().sum()

ACCIDENT_NO                    0
ACCIDENT_DATE                  0
ACCIDENT_TIME                  0
ACCIDENT_TYPE                  0
DAY_OF_WEEK                    0
DCA_CODE                       0
DCA_CODE_DESCRIPTION           0
LIGHT_CONDITION                0
POLICE_ATTEND                  0
ROAD_GEOMETRY                  0
SEVERITY                       0
SPEED_ZONE                     0
RUN_OFFROAD                    0
ROAD_NAME                    258
ROAD_TYPE                   2623
ROAD_ROUTE_1                  85
LGA_NAME                      90
DTP_REGION                    85
LATITUDE                      85
LONGITUDE                     85
VICGRID_X                     85
VICGRID_Y                     85
TOTAL_PERSONS                  0
INJ_OR_FATAL                   0
FATALITY                       0
SERIOUSINJURY                  0
OTHERINJURY                    0
NONINJURED                     0
MALES                          0
FEMALES                        0
BICYCLIST                      0
PASSENGER                      0
DRIVER                         0
PEDESTRIAN                     0
PILLION                        0
MOTORCYCLIST                   0
UNKNOWN                        0
PED_CYCLIST_5_12               0
PED_CYCLIST_13_18              0
OLD_PED_65_AND_OVER            0
OLD_DRIVER_75_AND_OVER         0
YOUNG_DRIVER_18_25             0
NO_OF_VEHICLES                 9
HEAVYVEHICLE                   9
PASSENGERVEHICLE               9
MOTORCYCLE                     9
PT_VEHICLE                     9
DEG_URBAN_NAME               990
SRNS                      137086
RMA                         8763
DIVIDED                     8763
STAT_DIV_NAME               1011
dtype: int64

In [57]:
crash_df.sample(5)

,ACCIDENT_NO,ACCIDENT_DATE,ACCIDENT_TIME,ACCIDENT_TYPE,DAY_OF_WEEK,DCA_CODE,DCA_CODE_DESCRIPTION,LIGHT_CONDITION,POLICE_ATTEND,ROAD_GEOMETRY,SEVERITY,SPEED_ZONE,RUN_OFFROAD,ROAD_NAME,ROAD_TYPE,ROAD_ROUTE_1,LGA_NAME,DTP_REGION,LATITUDE,LONGITUDE,VICGRID_X,VICGRID_Y,TOTAL_PERSONS,INJ_OR_FATAL,FATALITY,SERIOUSINJURY,OTHERINJURY,NONINJURED,MALES,FEMALES,BICYCLIST,PASSENGER,DRIVER,PEDESTRIAN,PILLION,MOTORCYCLIST,UNKNOWN,PED_CYCLIST_5_12,PED_CYCLIST_13_18,OLD_PED_65_AND_OVER,OLD_DRIVER_75_AND_OVER,YOUNG_DRIVER_18_25,NO_OF_VEHICLES,HEAVYVEHICLE,PASSENGERVEHICLE,MOTORCYCLE,PT_VEHICLE,DEG_URBAN_NAME,SRNS,RMA,DIVIDED,STAT_DIV_NAME
126151,T20210026863,2021-11-21,00:45:00,Struck Pedestrian,Sunday,100,PED NEAR SIDE. PED HIT BY VEHICLE FROM THE RIGHT.,Dark Street lights on,Yes,Cross intersection,Other injury accident,60 km/hr,No,PUNT,NaN,-1.0,MELBOURNE,INNER METRO,-37.845688,144.98503,2.498682e+06,2.406152e+06,2,1,0,0,1,1,2,0,0,0,1,1,0,0,0,0,0,1,0,0,1.0,0.0,1.0,0.0,0.0,MELB_URBAN,NaN,Arterial Highway,Undivided,Metro
130985,T20240032570,2024-12-19,11:45:00,Vehicle overturned (no collision),Thursday,184,OUT OF CONTROL ON CARRIAGEWAY (ON BEND),Day,Yes,Not at intersection,Serious injury accident,60 km/hr,No,BAILEY,ROAD,9999.0,CARDINIA,GREATER METRO,-37.936607,145.47570,2.541817e+06,2.395956e+06,1,1,0,1,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,1.0,0.0,0.0,1.0,0.0,MELB_URBAN,NaN,Local Road,Undivided,Metro
113659,T20180012831,2018-07-09,00:05:00,Collision with vehicle,Monday,110,CROSS TRAFFIC(INTERSECTIONS ONLY),Dark Street lights on,Yes,Multiple intersection,Other injury accident,80 km/hr,No,PLENTY VALLEY,HIGHWAY,2140.0,WHITTLESEA,GREATER METRO,-37.686172,145.06775,2.505976e+06,2.423853e+06,3,1,0,0,1,2,3,0,0,1,2,0,0,0,0,0,0,0,0,1,2.0,0.0,2.0,0.0,0.0,MELB_URBAN,M,Freeway,Divided,Metro
61179,T20250011588,2025-04-22,15:05:00,Collision with vehicle,Tuesday,130,REAR END(VEHICLES IN SAME LANE),Day,Yes,Not at intersection,Other injury accident,60 km/hr,No,HIGH,STREET,2530.0,BENDIGO,LODDON MALLEE,-36.774353,144.25629,2.433616e+06,2.524778e+06,2,2,0,0,2,0,1,1,0,0,2,0,0,0,0,0,0,0,0,0,2.0,0.0,2.0,0.0,0.0,LARGE_PROVINCIAL_CITIES,A,Arterial Highway,Undivided,Country
184604,T20170006648,2017-02-27,07:00:00,Collision with a fixed object,Monday,171,LEFT OFF CARRIAGEWAY INTO OBJECT/PARKED VEHICLE,Day,No,Not at intersection,Fatal accident,100 km/hr,Yes,ELMORE-BARNADOWN,ROAD,9999.0,BENDIGO,LODDON MALLEE,-36.560000,144.58444,2.462804e+06,2.548740e+06,1,1,1,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,1.0,0.0,1.0,0.0,0.0,RURAL_VICTORIA,NaN,NaN,NaN,Country

## 6. Quick look at important variables

## Useful Variables Identified

Based on initial exploration of the Victorian Road Crash dataset, the following variables have been identified as relevant for traffic accident risk prediction.

### ⏱️ Temporal Features
- ACCIDENT_DATE – Used to analyse trends over time (monthly/seasonal patterns)
- ACCIDENT_TIME – Useful for extracting hour of day (peak vs off-peak risk)
- DAY_OF_WEEK – Helps identify weekday vs weekend accident patterns

### 🚦 Accident Characteristics
- ACCIDENT_TYPE – Type of crash (e.g., collision, pedestrian-related)
- DCA_CODE_DESCRIPTION – Detailed crash classification providing deeper context
- SEVERITY – Indicates seriousness of accident (critical for risk analysis)
- LIGHT_CONDITION – Helps assess impact of daylight vs night conditions
- RUN_OFFROAD – Indicates whether the vehicle left the road

### 🛣️ Road & Environment Features
- SPEED_ZONE – Speed limit at accident location (key risk factor)
- ROAD_GEOMETRY – Type of road layout (intersection, straight, curve)
- ROAD_TYPE – Classification of road (highway, local road, etc.)
- ROAD_NAME – Useful for identifying specific high-risk roads
- RMA – Road management classification
- DIVIDED – Whether the road is divided or not

### 📍 Location Features
- LGA_NAME – Local Government Area (regional analysis)
- DTP_REGION – Broader transport region classification
- LATITUDE & LONGITUDE – Critical for mapping accident hotspots
- VICGRID_X & VICGRID_Y – Alternative spatial coordinates
- DEG_URBAN_NAME – Urban classification (urban vs regional)

### 🚗 Traffic & Vehicle Features
- NO_OF_VEHICLES – Number of vehicles involved in the crash
- HEAVYVEHICLE – Presence of heavy vehicles
- PASSENGERVEHICLE – Passenger vehicle involvement
- MOTORCYCLE – Motorcycle involvement
- PT_VEHICLE – Public transport vehicle involvement

### 👥 Casualty & Demographic Features
- TOTAL_PERSONS – Total number of people involved
- INJ_OR_FATAL – Indicator of injury or fatality occurrence
- FATALITY – Number of fatalities
- SERIOUSINJURY – Number of serious injuries
- OTHERINJURY – Number of minor injuries
- NONINJURED – Number of non-injured persons

### 👤 Road User Types
- DRIVER – Number of drivers involved
- PASSENGER – Number of passengers
- PEDESTRIAN – Number of pedestrians involved
- BICYCLIST – Number of cyclists involved
- MOTORCYCLIST – Number of motorcyclists
- PILLION – Motorcycle pillion passengers

### 🎯 Summary of Feature Importance

These variables collectively capture:
- Temporal patterns (when accidents happen)
- Environmental conditions (lighting, road structure)
- Spatial information (where accidents happen)
- Traffic composition (vehicle types involved)
- Human impact (injuries and fatalities)

This combination of features is essential for building a predictive model that can estimate accident risk across different locations and time periods.

## 7. Create a starter data dictionary

This is a practical project-level data dictionary for the variables most relevant to modelling.

In [61]:
data_dict = pd.DataFrame({
    "column_name": crash_df.columns,
    "data_type": crash_df.dtypes.astype(str).values
})

data_dict.head(10)

            column_name data_type
0           ACCIDENT_NO    object
1         ACCIDENT_DATE    object
2         ACCIDENT_TIME    object
3         ACCIDENT_TYPE    object
4           DAY_OF_WEEK    object
5              DCA_CODE     int64
6  DCA_CODE_DESCRIPTION    object
7       LIGHT_CONDITION    object
8         POLICE_ATTEND    object
9         ROAD_GEOMETRY    object

In [62]:
data_dictionary = pd.DataFrame({
    "column_name": [
        "ACCIDENT_DATE",
        "ACCIDENT_TIME",
        "DAY_OF_WEEK",
        "ACCIDENT_TYPE",
        "DCA_CODE_DESCRIPTION",
        "SEVERITY",
        "LIGHT_CONDITION",
        "SPEED_ZONE",
        "ROAD_GEOMETRY",
        "ROAD_TYPE",
        "LGA_NAME",
        "LATITUDE",
        "LONGITUDE",
        "NO_OF_VEHICLES",
        "TOTAL_PERSONS",
        "FATALITY",
        "SERIOUSINJURY",
        "OTHERINJURY",
        "PEDESTRIAN",
        "BICYCLIST",
        "MOTORCYCLIST"
    ],
    "description": [
        "Date on which the accident occurred",
        "Time at which the accident occurred",
        "Day of the week of the accident",
        "Type of accident (e.g., collision, pedestrian)",
        "Detailed description of crash classification",
        "Severity level of the accident",
        "Lighting condition at the time of accident",
        "Speed limit at accident location",
        "Road layout type (intersection, curve, etc.)",
        "Type/category of road",
        "Local Government Area of accident",
        "Latitude coordinate of accident location",
        "Longitude coordinate of accident location",
        "Number of vehicles involved in the accident",
        "Total number of persons involved",
        "Number of fatalities",
        "Number of serious injuries",
        "Number of other (minor) injuries",
        "Number of pedestrians involved",
        "Number of cyclists involved",
        "Number of motorcyclists involved"
    ]
})

data_dictionary

             column_name                                     description
0          ACCIDENT_DATE             Date on which the accident occurred
1          ACCIDENT_TIME             Time at which the accident occurred
2            DAY_OF_WEEK                 Day of the week of the accident
3          ACCIDENT_TYPE  Type of accident (e.g., collision, pedestrian)
4   DCA_CODE_DESCRIPTION    Detailed description of crash classification
5               SEVERITY                  Severity level of the accident
6        LIGHT_CONDITION      Lighting condition at the time of accident
7             SPEED_ZONE                Speed limit at accident location
8          ROAD_GEOMETRY    Road layout type (intersection, curve, etc.)
9              ROAD_TYPE                           Type/category of road
10              LGA_NAME               Local Government Area of accident
11              LATITUDE        Latitude coordinate of accident location
12             LONGITUDE       Longitude coordinate of accident location
13        NO_OF_VEHICLES     Number of vehicles involved in the accident
14         TOTAL_PERSONS                Total number of persons involved
15              FATALITY                            Number of fatalities
16         SERIOUSINJURY                      Number of serious injuries
17           OTHERINJURY                Number of other (minor) injuries
18            PEDESTRIAN                  Number of pedestrians involved
19             BICYCLIST                     Number of cyclists involved
20          MOTORCYCLIST                Number of motorcyclists involved

In [64]:
data_dictionary.to_csv("data_dictionary_accident.csv", index=False)

## 8. Summary

In this notebook, the Victorian Road Crash dataset was successfully imported and explored.

The dataset structure was examined by reviewing column names, data types, and sample records. Key variables relevant to traffic accident risk prediction were identified, including temporal features (date, time, day), road and environmental factors (speed zone, road geometry, lighting conditions), spatial attributes (latitude and longitude), and accident outcome indicators (severity, injuries, and fatalities).

A structured data dictionary was also created to document important variables and their meanings. This will support future stages of the project, including data cleaning, feature engineering, and model development.

Overall, this step establishes a strong foundation for building predictive models to identify high-risk intersections and accident patterns.

## 9. Deliverables completed
- Crash dataset imported
- Dataset columns explored
- Useful variables identified
- Starter data dictionary created