In [1]:
# WEB DEV TEAM PLEASE DELETE BEFORE PUBLISHING - DS TEAM PLEASE KEEP IN THE FINAL VERSION OF THE USE CASE

from IPython.core.display import HTML
HTML("""
<style>
@import url('https://fonts.googleapis.com/css2?family=Poppins:wght@600;700&family=Inter:wght@400;500&display=swap');

/* Global Fonts and Counters */
body, p, li, div {
    font-family: 'Inter', sans-serif;
}

body {
    counter-reset: h2counter;
}

/* Heading Fonts */
.usecase-header-bar,
.usecase-title,
.usecase-section-heading,
.usecase-sub-section-heading,
.usecase-sub-sub-section-heading,
.usecase-unnumbered-heading{
    font-family: 'Poppins', sans-serif;
}

.usecase-header-bar {
   padding: 16px 20px;
   background-color: #059669;
   color: #fff;
   border-radius: 6px 6px 0 0;
}

.usecase-title {
    font-size: 1.9em;
    font-weight: 800;
}

/* Metadata Styling */
.usecase-details {
    padding-left: 20px;
    padding-bottom: 8px;
    padding-top: 8px;
    font-size: 1.1em;
    color: #121212;
}

/* Base styling for all main headings (Numbered & Unnumbered) */
.usecase-section-heading, 
.usecase-unnumbered-heading {
    font-weight: 700;
    font-size: 1.35em;
    color: #059669;
    padding: 14px 4px 6px 4px;
    border-bottom: 3px solid #2DBE6C;
    margin-top: 10px;
}

/* Level 1 section headings */
.usecase-section-heading::before {
    content: none !important;
}

/* Level 2 subsection headings */
.usecase-sub-section-heading {
    font-weight: 600;
    font-size: 1.15em;
    color: #059669;
    margin-top: 8px;
}

.usecase-sub-section-heading::before {
    content: none !important;
}

/* Level 3 sub-subsection headings */
.usecase-sub-sub-section-heading {
    font-weight: 500;
    font-size: 1.05em;
    color: #059669;
    margin-top: 6px;
}

.usecase-sub-sub-section-heading::before {
    content: none !important;
}

/* Body */
.usecase-body {
    font-size: 1em;
    color: #121212;
    line-height: 1.6;
    margin-bottom: 8px;
}

/* Generic list styling */
.usecase-list {
    line-height: 1.7;
}

.usecase-list ul, .usecase-list ol {
    padding-left: 24px;
    margin-top: 8px;
    margin-bottom: 12px;
}

.usecase-list li {
    margin-bottom: 6px;
}

/* Datasets specific list box */
.usecase-datasets {
    background-color: rgba(5, 150, 105, 0.06);
    border-left: 4px solid #059669;
    padding: 12px 20px;
    border-radius: 0 4px 4px 0;
    margin-top: 12px;
}

.usecase-datasets ul {
    margin-top: 8px;
    margin-bottom: 8px;
}

/* Link styles for both TOC and Datasets */
.usecase-contents a, 
.usecase-datasets a {
    color: #059669;
    text-decoration: none;
}

.usecase-datasets a {
    font-weight: 500;
}

.usecase-contents a:hover, 
.usecase-datasets a:hover {
    text-decoration: underline;
}

/* TOC Container */
.usecase-contents {
    line-height: 1.9;
    padding-left: 20px;
}

/* Content Divider */
.usecase-code-divider {
    font-style: italic;
    color: rgba(18, 18, 18, 0.65);
    background-color: rgba(5, 150, 105, 0.06);
    padding: 10px 16px;
    border-radius: 4px;
    margin-top: 14px;
}
</style>

""")

<div class="usecase-header-bar">
    <div class="usecase-title">2023 Melbourne Liveability Assessment</div>
</div>

<div class="usecase-details"><b>Authored by: </b>Siju Deng</div>
<div class="usecase-details"><b>Date Created: </b>Trimester 3, 2023</div>
<div class="usecase-details"><b>Time to Complete:</b>120 mins</div>
<div class="usecase-details"><b>Level: </b>Beginner</div>
<div class="usecase-details"><b>Pre-requisite Skills: </b>Basic Python, pandas and introductory data analysis</div>

<div id="scenario" class="usecase-unnumbered-heading"><b>Scenario</b></div>

<div class="usecase-body">

As a current or prospective City of Melbourne resident, I want to compare population, housing and access to local infrastructure so that I can identify areas that may offer a more comfortable living environment.

As a City of Melbourne planner, I want to identify areas experiencing greater pressure on pedestrian infrastructure, public facilities and dining capacity so that future investment can be better targeted.

</div>

<div id="what-this-teaches" class="usecase-unnumbered-heading"><b>What this usecase will teach you</b></div>

<div class="usecase-list">

- Import and prepare geospatial datasets using GeoPandas.
- Merge spatial and tabular datasets for urban analysis.
- Perform spatial joins and coordinate reference system (CRS) transformations.
- Create interactive maps using Folium.
- Calculate and compare liveability indicators across SA2 areas.
- Interpret geospatial analysis results to support urban planning decisions.

</div>

<div id="background" class="usecase-unnumbered-heading"><b>Background</b></div>

<div class="usecase-body">
This analysis combines population, residential dwelling, pedestrian-network, public-facility and café/restaurant seating data. It first visualises where people and dwellings are concentrated, then calculates three simple pressure indicators: residents per metre of pedestrian network, residents per public facility and residents per dining seat.

The indicators are normalised and combined with equal weights to produce an exploratory liveability score. The score is intended as a transparent demonstration of spatial analysis rather than a definitive measure of quality of life. Non-residential areas are excluded from the final scoring so that industrial or unpopulated zones do not distort the comparison.
</div>

<div id="data-sets" class="usecase-unnumbered-heading"><b>Data Sets</b></div>

<div class="usecase-datasets">

- [Residential dwellings — City of Melbourne Open Data](https://data.melbourne.vic.gov.au/explore/dataset/residential-dwellings/)
- [Pedestrian network — City of Melbourne Open Data](https://data.melbourne.vic.gov.au/explore/dataset/pedestrian-network/)
- [Landmarks and places of interest — City of Melbourne Open Data](https://data.melbourne.vic.gov.au/explore/dataset/landmarks-and-places-of-interest-including-schools-theatres-health-services-spor/)
- [Cafés and restaurants with seating capacity — City of Melbourne Open Data](https://data.melbourne.vic.gov.au/explore/dataset/cafes-and-restaurants-with-seating-capacity/)
- [Regional population, 2021–22 — Australian Bureau of Statistics](https://www.abs.gov.au/statistics/people/population/regional-population/2021-22)
- [ASGS Edition 3 digital boundary files — Australian Bureau of Statistics](https://www.abs.gov.au/statistics/standards/australian-statistical-geography-standard-asgs-edition-3/jul2021-jun2026/access-and-downloads/digital-boundary-files)

</div>

<div class="usecase-contents"><b>Contents</b></div>

<div class="usecase-contents">

1. <a href="#section-1">Set up the Python environment</a><br>
2. <a href="#section-2">Load City of Melbourne boundary data</a><br>
3. <a href="#section-3">Prepare population and residential data</a><br>
&nbsp;&nbsp;&nbsp;&nbsp;3.1. <a href="#section-3-1">Residential dwellings</a><br>
&nbsp;&nbsp;&nbsp;&nbsp;3.2. <a href="#section-3-2">Population statistics</a><br>
4. <a href="#section-4">Merge and validate spatial data</a><br>
&nbsp;&nbsp;&nbsp;&nbsp;4.1. <a href="#section-4-1">Population and boundary data</a><br>
&nbsp;&nbsp;&nbsp;&nbsp;4.2. <a href="#section-4-2">Residential data and boundaries</a><br>
5. <a href="#section-5">Visualise population and residential patterns</a><br>
&nbsp;&nbsp;&nbsp;&nbsp;5.1. <a href="#section-5-1">Population density</a><br>
&nbsp;&nbsp;&nbsp;&nbsp;5.2. <a href="#section-5-2">Residential locations</a><br>
&nbsp;&nbsp;&nbsp;&nbsp;5.3. <a href="#section-5-3">Residential heat map</a><br>
6. <a href="#section-6">Calculate infrastructure-pressure indicators</a><br>
&nbsp;&nbsp;&nbsp;&nbsp;6.1. <a href="#section-6-1">Pedestrian-network pressure</a><br>
&nbsp;&nbsp;&nbsp;&nbsp;6.2. <a href="#section-6-2">Public-facility pressure</a><br>
&nbsp;&nbsp;&nbsp;&nbsp;6.3. <a href="#section-6-3">Dining-seat pressure</a><br>
7. <a href="#section-7">Calculate and validate the liveability score</a><br>
&nbsp;&nbsp;&nbsp;&nbsp;7.1. <a href="#section-7-1">Validation checks</a><br>
8. <a href="#conclusion">Conclusion</a><br>

</div>

<div class="usecase-section-heading">
    1. Set up the Python environment
</div>

<div class="usecase-body">
Import the libraries required for data retrieval, geospatial processing, spatial analysis and interactive mapping throughout the use case.
</div>

In [2]:
import os
import tempfile
from io import BytesIO
from zipfile import ZipFile

import folium
import geopandas as gpd
import numpy as np
import pandas as pd
import requests
from branca.colormap import LinearColormap
from folium.plugins import FastMarkerCluster, HeatMap
from IPython.display import display
from shapely.geometry import box
from sklearn.preprocessing import MinMaxScaler

<div class="usecase-section-heading">
    2. Load City of Melbourne boundary data
</div>

<div class="usecase-body">
Load the Australian Statistical Geography Standard (ASGS) SA2 boundary file and retain the SA2 areas that belong to the Melbourne City SA3 region. The request is validated before the ZIP archive is read.
</div>

In [3]:
zip_url = (
    "https://www.abs.gov.au/statistics/standards/"
    "australian-statistical-geography-standard-asgs-edition-3/"
    "jul2021-jun2026/access-and-downloads/digital-boundary-files/"
    "SA2_2021_AUST_SHP_GDA2020.zip"
)

response = requests.get(zip_url, timeout=60)
response.raise_for_status()

with tempfile.TemporaryDirectory() as temp_dir:
    with ZipFile(BytesIO(response.content)) as zip_file:
        zip_file.extractall(temp_dir)

    shapefile_name = next(
        filename for filename in os.listdir(temp_dir) if filename.endswith(".shp")
    )
    LGAgdf = gpd.read_file(os.path.join(temp_dir, shapefile_name))

display(LGAgdf.head())

,SA2_CODE21,SA2_NAME21,CHG_FLAG21,CHG_LBL21,SA3_CODE21,SA3_NAME21,SA4_CODE21,SA4_NAME21,GCC_CODE21,GCC_NAME21,STE_CODE21,STE_NAME21,AUS_CODE21,AUS_NAME21,AREASQKM21,LOCI_URI21,geometry
0,101021007,Braidwood,0,No change,10102,Queanbeyan,101,Capital Region,1RNSW,Rest of NSW,1,New South Wales,AUS,Australia,3418.3525,http://linked.data.gov.au/dataset/asgsed3/SA2/...,"POLYGON ((149.58424 -35.44426, 149.58444 -35.4..."
1,101021008,Karabar,0,No change,10102,Queanbeyan,101,Capital Region,1RNSW,Rest of NSW,1,New South Wales,AUS,Australia,6.9825,http://linked.data.gov.au/dataset/asgsed3/SA2/...,"POLYGON ((149.21899 -35.36738, 149.218 -35.366..."
2,101021009,Queanbeyan,0,No change,10102,Queanbeyan,101,Capital Region,1RNSW,Rest of NSW,1,New South Wales,AUS,Australia,4.7620,http://linked.data.gov.au/dataset/asgsed3/SA2/...,"POLYGON ((149.21326 -35.34325, 149.21619 -35.3..."
3,101021010,Queanbeyan - East,0,No change,10102,Queanbeyan,101,Capital Region,1RNSW,Rest of NSW,1,New South Wales,AUS,Australia,13.0032,http://linked.data.gov.au/dataset/asgsed3/SA2/...,"POLYGON ((149.24034 -35.34781, 149.24024 -35.3..."
4,101021012,Queanbeyan West - Jerrabomberra,0,No change,10102,Queanbeyan,101,Capital Region,1RNSW,Rest of NSW,1,New South Wales,AUS,Australia,13.6748,http://linked.data.gov.au/dataset/asgsed3/SA2/...,"POLYGON ((149.19572 -35.36126, 149.1997 -35.35..."

<div class="usecase-body">
Check the SA3 code data type before filtering so the boundary code can be compared reliably with the Melbourne City SA3 code. If one value is stored as text and the other as a number, the filter may fail even when the codes appear identical.
</div>

In [4]:
print(f"SA3 code data type: {LGAgdf['SA3_CODE21'].dtype}")

SA3 code data type: object

<div class="usecase-body">
Convert the SA3 code to numeric format so it can be compared consistently with the target Melbourne City SA3 code (20604). This ensures the correct SA2 boundary records are retained for the study area.
</div>

In [5]:
LGAgdf["SA3_CODE21"] = pd.to_numeric(LGAgdf["SA3_CODE21"], errors="coerce")
filtered_LGAgdf = LGAgdf.loc[LGAgdf["SA3_CODE21"] == 20604].copy()

assert not filtered_LGAgdf.empty, "No SA2 boundaries were found for SA3 code 20604."
display(filtered_LGAgdf.head())

,SA2_CODE21,SA2_NAME21,CHG_FLAG21,CHG_LBL21,SA3_CODE21,SA3_NAME21,SA4_CODE21,SA4_NAME21,GCC_CODE21,GCC_NAME21,STE_CODE21,STE_NAME21,AUS_CODE21,AUS_NAME21,AREASQKM21,LOCI_URI21,geometry
771,206041117,Carlton,0,No change,20604.0,Melbourne City,206,Melbourne - Inner,2GMEL,Greater Melbourne,2,Victoria,AUS,Australia,1.8187,http://linked.data.gov.au/dataset/asgsed3/SA2/...,"POLYGON ((144.97488 -37.79794, 144.97477 -37.7..."
772,206041118,Docklands,0,No change,20604.0,Melbourne City,206,Melbourne - Inner,2GMEL,Greater Melbourne,2,Victoria,AUS,Australia,2.4440,http://linked.data.gov.au/dataset/asgsed3/SA2/...,"POLYGON ((144.94525 -37.81208, 144.94545 -37.8..."
773,206041119,East Melbourne,0,No change,20604.0,Melbourne City,206,Melbourne - Inner,2GMEL,Greater Melbourne,2,Victoria,AUS,Australia,2.8998,http://linked.data.gov.au/dataset/asgsed3/SA2/...,"POLYGON ((144.97396 -37.8133, 144.97363 -37.81..."
774,206041120,Flemington Racecourse,0,No change,20604.0,Melbourne City,206,Melbourne - Inner,2GMEL,Greater Melbourne,2,Victoria,AUS,Australia,1.7093,http://linked.data.gov.au/dataset/asgsed3/SA2/...,"POLYGON ((144.91598 -37.78187, 144.91698 -37.7..."
775,206041121,Kensington (Vic.),0,No change,20604.0,Melbourne City,206,Melbourne - Inner,2GMEL,Greater Melbourne,2,Victoria,AUS,Australia,2.1470,http://linked.data.gov.au/dataset/asgsed3/SA2/...,"POLYGON ((144.92172 -37.78987, 144.92243 -37.7..."

In [6]:
print(f"SA2 boundary rows retained: {len(filtered_LGAgdf)}")

SA2 boundary rows retained: 16

<div class="usecase-section-heading"><b>3. Prepare population and residential data</b></div>

<div class="usecase-body">
Prepare the population and residential datasets so they use consistent formats and geographic information before spatial analysis.
</div>

<div id="section-3-1" class="usecase-sub-section-heading"><b>3.1 Residential dwellings</b></div>

<div class="usecase-body">
Load the residential dwelling data and prepare its coordinates for spatial analysis within the City of Melbourne.
</div>

In [7]:
residential_csv_url = (
    "https://data.melbourne.vic.gov.au/api/explore/v2.1/catalog/"
    "datasets/residential-dwellings/exports/csv"
    "?lang=en&timezone=Australia%2FSydney&use_labels=true&delimiter=%2C"
)
residential_df = pd.read_csv(residential_csv_url)

required_columns = {"Longitude", "Latitude", "Dwelling number", "CLUE small area"}
missing_columns = required_columns.difference(residential_df.columns)
assert not missing_columns, f"Missing residential columns: {sorted(missing_columns)}"

display(residential_df.head())

,Census year,Block ID,Property ID,Base property ID,Building address,CLUE small area,Dwelling type,Dwelling number,Longitude,Latitude,location
0,2011,358,101543,101543,158 Capel Street NORTH MELBOURNE 3051,North Melbourne,House/Townhouse,1,144.955691,-37.804359,"-37.804359, 144.955690933"
1,2011,358,101544,101544,156 Capel Street NORTH MELBOURNE 3051,North Melbourne,House/Townhouse,1,144.955683,-37.804403,"-37.80440328, 144.955683349"
2,2011,358,101557,101557,122 Capel Street NORTH MELBOURNE 3051,North Melbourne,House/Townhouse,1,144.955545,-37.805165,"-37.80516456, 144.955545217"
3,2011,358,101560,101560,108-112 Capel Street NORTH MELBOURNE 3051,North Melbourne,Student Apartments,12,144.955501,-37.805411,"-37.80541067, 144.955500719"
4,2011,358,107496,107496,139 Peel Street NORTH MELBOURNE 3051,North Melbourne,House/Townhouse,1,144.955838,-37.804788,"-37.80478808, 144.955837659"

<div class="usecase-body">
The residential dataset initially contains longitude and latitude as ordinary numeric columns. Converting these coordinates into a GeoDataFrame gives each record a spatial geometry and coordinate reference system (CRS), which is required for spatial joins, mapping and geographic comparisons later in the analysis.
</div>

<div class="usecase-body">
    Convert the longitude and latitude fields into a `GeoDataFrame` using the WGS 84 coordinate reference system (`EPSG:4326`).
</div>

In [8]:
RESgdf = gpd.GeoDataFrame(
    residential_df,
    geometry=gpd.points_from_xy(
        residential_df["Longitude"], residential_df["Latitude"]
    ),
    crs="EPSG:4326",
)

display(RESgdf.head())

,Census year,Block ID,Property ID,Base property ID,Building address,CLUE small area,Dwelling type,Dwelling number,Longitude,Latitude,location,geometry
0,2011,358,101543,101543,158 Capel Street NORTH MELBOURNE 3051,North Melbourne,House/Townhouse,1,144.955691,-37.804359,"-37.804359, 144.955690933",POINT (144.95569 -37.80436)
1,2011,358,101544,101544,156 Capel Street NORTH MELBOURNE 3051,North Melbourne,House/Townhouse,1,144.955683,-37.804403,"-37.80440328, 144.955683349",POINT (144.95568 -37.8044)
2,2011,358,101557,101557,122 Capel Street NORTH MELBOURNE 3051,North Melbourne,House/Townhouse,1,144.955545,-37.805165,"-37.80516456, 144.955545217",POINT (144.95555 -37.80516)
3,2011,358,101560,101560,108-112 Capel Street NORTH MELBOURNE 3051,North Melbourne,Student Apartments,12,144.955501,-37.805411,"-37.80541067, 144.955500719",POINT (144.9555 -37.80541)
4,2011,358,107496,107496,139 Peel Street NORTH MELBOURNE 3051,North Melbourne,House/Townhouse,1,144.955838,-37.804788,"-37.80478808, 144.955837659",POINT (144.95584 -37.80479)

<div class="usecase-sub-section-heading">
3.2. Population statistics
</div>

<div class="usecase-body">
Load, clean and filter the population data to retain the records required for the City of Melbourne analysis.
</div>

<div class="usecase-body">
The ABS workbook uses multiple heading rows, so these rows are combined into a single set of meaningful column names. This makes the dataset easier to filter, reference and merge with the spatial boundary data.
</div>

In [9]:
population_excel_url = (
    "https://www.abs.gov.au/statistics/people/population/regional-population/"
    "2021-22/32180DS0001_2021-22r.xlsx"
)
sheet_name = "Table 2"

header_df = pd.read_excel(
    population_excel_url, sheet_name=sheet_name, header=None, nrows=8
)
combined_header = header_df.iloc[5:8].apply(
    lambda column: " ".join(column.dropna().astype(str)), axis=0
)
population_df = pd.read_excel(
    population_excel_url, sheet_name=sheet_name, skiprows=8, header=None
)
population_df.columns = combined_header

display(population_df.head())

,S/T code,S/T name,GCCSA code,GCCSA name,SA4 code,SA4 name,SA3 code,SA3 name,SA2 code,SA2 name,...,,ERP change 2021-22 no.,%,,Components of population change 2021-22 Natural increase no.,Net internal migration no.,Net overseas migration no.,,Area km2,Population density 2022 persons/km2
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,Victoria,2RVIC,Rest of Vic.,201.0,Ballarat,20101.0,Ballarat,201011001.0,Alfredton,...,NaN,1150.0,6.8,NaN,169.0,899.0,82.0,NaN,52.7,341.3
2,2,Victoria,2RVIC,Rest of Vic.,201.0,Ballarat,20101.0,Ballarat,201011002.0,Ballarat,...,NaN,-140.0,-1.2,NaN,-83.0,-134.0,77.0,NaN,12.4,963.8
3,2,Victoria,2RVIC,Rest of Vic.,201.0,Ballarat,20101.0,Ballarat,201011005.0,Buninyong,...,NaN,15.0,0.2,NaN,32.0,-53.0,36.0,NaN,51.6,140.4
4,2,Victoria,2RVIC,Rest of Vic.,201.0,Ballarat,20101.0,Ballarat,201011006.0,Delacombe,...,NaN,1142.0,10.7,NaN,123.0,996.0,23.0,NaN,34.2,345.1

<div class="usecase-body">
Filter the dataset to Victoria so records from other Australian states and territories do not enter the Melbourne analysis.
</div>

In [10]:
state_code_column = "S/T code"
victoria_population = population_df.loc[
    population_df[state_code_column].eq(2)
].dropna(subset=[state_code_column])

<div class="usecase-body">
Retain only records from the Melbourne City SA3 region (20604). This keeps the population dataset aligned with the same geographic study area used for the boundary data.
</div>

In [11]:
sa3_code_column = "SA3 code"
filtered_sa3_df = victoria_population.loc[
    victoria_population[sa3_code_column].eq(20604)
].copy()

assert not filtered_sa3_df.empty, "No population records were found for SA3 code 20604."
display(filtered_sa3_df.head())

,S/T code,S/T name,GCCSA code,GCCSA name,SA4 code,SA4 name,SA3 code,SA3 name,SA2 code,SA2 name,...,,ERP change 2021-22 no.,%,,Components of population change 2021-22 Natural increase no.,Net internal migration no.,Net overseas migration no.,,Area km2,Population density 2022 persons/km2
128,2,Victoria,2GMEL,Greater Melbourne,206.0,Melbourne - Inner,20604.0,Melbourne City,206041117.0,Carlton,...,NaN,940.0,5.5,NaN,14.0,-610.0,1536.0,NaN,1.8,9899.4
129,2,Victoria,2GMEL,Greater Melbourne,206.0,Melbourne - Inner,20604.0,Melbourne City,206041118.0,Docklands,...,NaN,551.0,3.5,NaN,179.0,-31.0,403.0,NaN,2.4,6733.2
130,2,Victoria,2GMEL,Greater Melbourne,206.0,Melbourne - Inner,20604.0,Melbourne City,206041119.0,East Melbourne,...,NaN,-75.0,-1.5,NaN,-10.0,-139.0,74.0,NaN,2.9,1684.3
131,2,Victoria,2GMEL,Greater Melbourne,206.0,Melbourne - Inner,20604.0,Melbourne City,206041120.0,Flemington Racecourse,...,NaN,0.0,0.0,NaN,0.0,0.0,0.0,NaN,1.7,45.6
132,2,Victoria,2GMEL,Greater Melbourne,206.0,Melbourne - Inner,20604.0,Melbourne City,206041121.0,Kensington (Vic.),...,NaN,128.0,1.2,NaN,102.0,-114.0,140.0,NaN,2.1,5123.4

<div class="usecase-body">
    Create a working copy so the filtered source data remains unchanged.
</div>

In [12]:
filtered_sa3_df_copy = filtered_sa3_df.copy()

<div class="usecase-body">
    Estimate the 2022 population of each SA2 by multiplying population density by area.
</div>

In [13]:
filtered_sa3_df_copy["Total Population"] = (
    filtered_sa3_df_copy["Population density 2022 persons/km2"]
    * filtered_sa3_df_copy["Area km2"]
)

display(filtered_sa3_df_copy[["SA2 name", "Total Population"]].head())

                  SA2 name  Total Population
128                Carlton          17818.92
129              Docklands          16159.68
130         East Melbourne           4884.47
131  Flemington Racecourse             77.52
132      Kensington (Vic.)          10759.14

<div class="usecase-body">
Remove higher-level geographic fields and empty columns that are no longer required. This reduces clutter and keeps only the variables needed for the SA2-level liveability analysis.
</div>

In [14]:
columns_to_drop = [
    "S/T code", "S/T name", "GCCSA code", "GCCSA name",
    "SA4 code", "SA4 name", "SA3 code", "SA3 name",
]
filtered_sa3_df_copy = filtered_sa3_df_copy.drop(columns=columns_to_drop)
filtered_sa3_df_copy = filtered_sa3_df_copy.dropna(axis=1, how="all")

In [15]:
display(filtered_sa3_df_copy.head())

,SA2 code,SA2 name,ERP at 30 June 2021 no.,2022 no.,ERP change 2021-22 no.,%,Components of population change 2021-22 Natural increase no.,Net internal migration no.,Net overseas migration no.,Area km2,Population density 2022 persons/km2,Total Population
128,206041117.0,Carlton,17064.0,18004.0,940.0,5.5,14.0,-610.0,1536.0,1.8,9899.4,17818.92
129,206041118.0,Docklands,15905.0,16456.0,551.0,3.5,179.0,-31.0,403.0,2.4,6733.2,16159.68
130,206041119.0,East Melbourne,4959.0,4884.0,-75.0,-1.5,-10.0,-139.0,74.0,2.9,1684.3,4884.47
131,206041120.0,Flemington Racecourse,78.0,78.0,0.0,0.0,0.0,0.0,0.0,1.7,45.6,77.52
132,206041121.0,Kensington (Vic.),10872.0,11000.0,128.0,1.2,102.0,-114.0,140.0,2.1,5123.4,10759.14

<div class="usecase-section-heading">
4. Merge and validate spatial data
</div>

<div class="usecase-body">
Combine the prepared datasets using consistent geographic areas and validate the results before further analysis.
</div>

<div class="usecase-sub-section-heading">
4.1. Population and boundary data
</div>

<div class="usecase-body">
Match the population records with their corresponding SA2 boundaries to create a spatial population dataset.
</div>

In [16]:
population_sa2_names = set(filtered_sa3_df_copy["SA2 name"].dropna().unique())
boundary_sa2_names = set(filtered_LGAgdf["SA2_NAME21"].dropna().unique())

print(f"Population SA2 areas: {len(population_sa2_names)}")
print(f"Boundary SA2 areas: {len(boundary_sa2_names)}")

Population SA2 areas: 16
Boundary SA2 areas: 16

<div class="usecase-body">
The SA2 names from both datasets are compared to identify any unmatched areas before the merge. If names differ because of spelling or formatting, those differences must be resolved first to avoid missing spatial records.
</div>

In [17]:
common_sa2_names = population_sa2_names & boundary_sa2_names
population_only = population_sa2_names - boundary_sa2_names
boundary_only = boundary_sa2_names - population_sa2_names

print(f"Matching SA2 names: {len(common_sa2_names)}")
print(f"Population-only names: {sorted(population_only)}")
print(f"Boundary-only names: {sorted(boundary_only)}")

Matching SA2 names: 16
Population-only names: []
Boundary-only names: []

<div class="usecase-body">
Review the differences between the two name sets. Matching names can be merged directly; unmatched names are reported for validation.
</div>

<div class="usecase-body">
Once the SA2 names are confirmed to match, the population data is joined to the SA2 boundary polygons. This creates a spatial dataset in which each area contains both population information and geographic geometry for later mapping and analysis.
</div>

In [18]:
merged_data = pd.merge(
    filtered_sa3_df_copy,
    filtered_LGAgdf[['SA2_NAME21', 'geometry']],
    left_on='SA2 name',
    right_on='SA2_NAME21',
    how='left'
)
merged_data.drop(columns='SA2_NAME21', inplace=True)

In [19]:
# Display
display(merged_data)

,SA2 code,SA2 name,ERP at 30 June 2021 no.,2022 no.,ERP change 2021-22 no.,%,Components of population change 2021-22 Natural increase no.,Net internal migration no.,Net overseas migration no.,Area km2,Population density 2022 persons/km2,Total Population,geometry
0,206041117.0,Carlton,17064.0,18004.0,940.0,5.5,14.0,-610.0,1536.0,1.8,9899.4,17818.92,"POLYGON ((144.97488 -37.79794, 144.97477 -37.7..."
1,206041118.0,Docklands,15905.0,16456.0,551.0,3.5,179.0,-31.0,403.0,2.4,6733.2,16159.68,"POLYGON ((144.94525 -37.81208, 144.94545 -37.8..."
2,206041119.0,East Melbourne,4959.0,4884.0,-75.0,-1.5,-10.0,-139.0,74.0,2.9,1684.3,4884.47,"POLYGON ((144.97396 -37.8133, 144.97363 -37.81..."
3,206041120.0,Flemington Racecourse,78.0,78.0,0.0,0.0,0.0,0.0,0.0,1.7,45.6,77.52,"POLYGON ((144.91598 -37.78187, 144.91698 -37.7..."
4,206041121.0,Kensington (Vic.),10872.0,11000.0,128.0,1.2,102.0,-114.0,140.0,2.1,5123.4,10759.14,"POLYGON ((144.92172 -37.78987, 144.92243 -37.7..."
5,206041124.0,Parkville,7428.0,7462.0,34.0,0.5,-8.0,-177.0,219.0,4.0,1842.9,7371.60,"POLYGON ((144.93897 -37.78156, 144.93874 -37.7..."
6,206041125.0,South Yarra - West,6536.0,6565.0,29.0,0.4,4.0,-70.0,95.0,1.5,4368.8,6553.20,"POLYGON ((144.97455 -37.83467, 144.97445 -37.8..."
7,206041127.0,West Melbourne - Industrial,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6.2,0.0,0.00,"POLYGON ((144.90759 -37.80612, 144.90769 -37.8..."
8,206041503.0,Melbourne CBD - East,10119.0,10655.0,536.0,5.3,34.0,-74.0,576.0,0.8,13285.5,10628.40,"POLYGON ((144.96534 -37.81137, 144.96576 -37.8..."
9,206041504.0,Melbourne CBD - North,17360.0,18826.0,1466.0,8.4,57.0,482.0,927.0,0.6,33522.1,20113.26,"POLYGON ((144.95569 -37.80771, 144.95599 -37.8..."
10,206041505.0,Melbourne CBD - West,16098.0,17299.0,1201.0,7.5,71.0,333.0,797.0,1.0,17211.2,17211.20,"POLYGON ((144.9528 -37.8161, 144.95235 -37.815..."
11,206041506.0,North Melbourne,15945.0,16582.0,637.0,4.0,64.0,-131.0,704.0,2.4,6838.5,16412.40,"POLYGON ((144.93585 -37.79507, 144.93569 -37.7..."
12,206041507.0,Royal Botanic Gardens Victoria,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.4,0.0,0.00,"POLYGON ((144.97665 -37.82318, 144.97743 -37.8..."
13,206041508.0,Southbank (West) - South Wharf,6607.0,6814.0,207.0,3.1,31.0,15.0,161.0,0.8,8020.2,6416.16,"POLYGON ((144.96478 -37.8197, 144.96539 -37.81..."
14,206041509.0,Southbank - East,16506.0,17340.0,834.0,5.1,134.0,315.0,385.0,0.8,21567.2,17253.76,"POLYGON ((144.96589 -37.8218, 144.96622 -37.82..."
15,206041510.0,West Melbourne - Residential,7614.0,8014.0,400.0,5.3,46.0,169.0,185.0,0.8,9717.5,7774.00,"POLYGON ((144.94264 -37.80731, 144.94285 -37.8..."

<div class="usecase-body">
Check whether any merged records are missing geographic boundary information.
</div>

In [20]:
missing_geometry = merged_data[merged_data['geometry'].isna()]
# Display
display(missing_geometry)

Empty DataFrame
Columns: [SA2 code, SA2 name, ERP at 30 June 2021 no., 2022 no., ERP change 2021-22 no., %, Components of population change 2021-22 Natural increase no., Net internal migration no., Net overseas migration no., Area km2, Population density 2022 persons/km2, Total Population, geometry]
Index: []

<div class="usecase-body">
No missing geometries were found.
</div>

<div class="usecase-sub-section-heading">
4.2. Residential data and boundaries
</div>

<div class="usecase-body">
Assign residential dwelling locations to their corresponding SA2 boundaries for area-based analysis.
</div>

In [21]:
residential_area_names = RESgdf["CLUE small area"].dropna().unique()
print(f"Residential source areas: {len(residential_area_names)}")

Residential source areas: 13

<div class="usecase-body">
The residential dataset uses different area labels from the ABS SA2 boundaries, so matching by text alone would be unreliable. A spatial join uses each dwelling's coordinates to determine which SA2 polygon physically contains it, giving every dwelling a consistent SA2 classification.
</div>

In [22]:
sa2_name_set = set(filtered_sa3_df_copy["SA2 name"].dropna().unique())
residential_area_set = set(RESgdf["CLUE small area"].dropna().unique())

print(f"Matching names: {len(sa2_name_set & residential_area_set)}")
print(f"SA2-only names: {sorted(sa2_name_set - residential_area_set)}")
print(f"Residential-data-only names: {sorted(residential_area_set - sa2_name_set)}")

Matching names: 5
SA2-only names: ['Flemington Racecourse', 'Kensington (Vic.)', 'Melbourne CBD - East', 'Melbourne CBD - North', 'Melbourne CBD - West', 'Royal Botanic Gardens Victoria', 'South Yarra - West', 'Southbank (West) - South Wharf', 'Southbank - East', 'West Melbourne - Industrial', 'West Melbourne - Residential']
Residential-data-only names: ['Kensington', 'Melbourne (CBD)', 'Melbourne (Remainder)', 'Port Melbourne', 'South Yarra', 'Southbank', 'West Melbourne (Industrial)', 'West Melbourne (Residential)']

<div class="usecase-body">
The datasets use different area-field names, so the boundary polygons are used to assign a consistent SA2 name to each residential record.
</div>

In [23]:
# Convert to GeoDataFrame
RESgdf_geo = gpd.GeoDataFrame(RESgdf, geometry='geometry', crs="epsg:4326")
merged_data_geo = gpd.GeoDataFrame(merged_data, geometry='geometry', crs="epsg:4326")

In [24]:
# # connect
residential_with_area = gpd.sjoin(
    RESgdf_geo,
    merged_data_geo[['geometry', 'SA2 name']],
    how='inner',
    predicate='within'
)

# update
residential_with_area['CLUE small area'] = residential_with_area['SA2 name']
residential_with_area.drop(columns='SA2 name', inplace=True)

In [25]:
# Display
display(residential_with_area)

,Census year,Block ID,Property ID,Base property ID,Building address,CLUE small area,Dwelling type,Dwelling number,Longitude,Latitude,location,geometry,index_right
0,2011,358,101543,101543,158 Capel Street NORTH MELBOURNE 3051,North Melbourne,House/Townhouse,1,144.955691,-37.804359,"-37.804359, 144.955690933",POINT (144.95569 -37.80436),11
1,2011,358,101544,101544,156 Capel Street NORTH MELBOURNE 3051,North Melbourne,House/Townhouse,1,144.955683,-37.804403,"-37.80440328, 144.955683349",POINT (144.95568 -37.8044),11
2,2011,358,101557,101557,122 Capel Street NORTH MELBOURNE 3051,North Melbourne,House/Townhouse,1,144.955545,-37.805165,"-37.80516456, 144.955545217",POINT (144.95555 -37.80516),11
3,2011,358,101560,101560,108-112 Capel Street NORTH MELBOURNE 3051,North Melbourne,Student Apartments,12,144.955501,-37.805411,"-37.80541067, 144.955500719",POINT (144.9555 -37.80541),11
4,2011,358,107496,107496,139 Peel Street NORTH MELBOURNE 3051,North Melbourne,House/Townhouse,1,144.955838,-37.804788,"-37.80478808, 144.955837659",POINT (144.95584 -37.80479),11
...,...,...,...,...,...,...,...,...,...,...,...,...,...
219675,2023,228,107705,107705,79 Princes Street CARLTON VIC 3053,Carlton,House/Townhouse,1,144.972884,-37.792989,"-37.79298926, 144.972883743",POINT (144.97288 -37.79299),0
219676,2023,228,107709,107709,87 Princes Street CARLTON VIC 3053,Carlton,House/Townhouse,1,144.972662,-37.792967,"-37.79296657, 144.972662056",POINT (144.97266 -37.79297),0
219677,2023,228,107712,107712,93 Princes Street CARLTON VIC 3053,Carlton,House/Townhouse,1,144.972496,-37.792947,"-37.79294703, 144.972495857",POINT (144.9725 -37.79295),0
219678,2023,228,107713,107713,95 Princes Street CARLTON VIC 3053,Carlton,House/Townhouse,1,144.972442,-37.792942,"-37.79294197, 144.972441506",POINT (144.97244 -37.79294),0
219679,2023,228,107716,107716,101 Princes Street CARLTON VIC 3053,Carlton,House/Townhouse,1,144.972273,-37.792924,"-37.79292407, 144.972272635",POINT (144.97227 -37.79292),0

<div class="usecase-section-heading">
5. Visualise population and residential patterns
</div>

<div class="usecase-body">
Visualise population and residential patterns across the study area to explore how people and dwellings are spatially distributed.
</div>

In [26]:
# highlight on map
def highlight_function(feature):
    return {
        'color': 'black',
        'weight': 3,
    }

<div class="usecase-body">
    Define reusable functions for drawing consistently styled polygon layers and legends.
</div>

In [27]:
def draw_map(existing_map, data, value_column, colour_scale, tooltip_formatter, add_colormap=True):
    """Add a consistently styled polygon layer to an existing Folium map."""
    valid_values = data[value_column].replace([np.inf, -np.inf], np.nan).dropna()
    if valid_values.empty:
        raise ValueError(f"No valid values are available for {value_column!r}.")

    colormap = LinearColormap(
        colors=colour_scale,
        vmin=float(valid_values.min()),
        vmax=float(valid_values.max()),
        caption=value_column.replace("_", " ").title(),
    )
    if add_colormap:
        colormap.add_to(existing_map)

    for _, row in data.iterrows():
        value = row[value_column]
        colour = "#ffffff00" if pd.isna(value) else colormap(value)
        folium.GeoJson(
            row["geometry"],
            style_function=lambda feature, colour=colour: {
                "fillColor": colour,
                "color": "black",
                "weight": 0.5,
                "fillOpacity": 0.7 if colour != "#ffffff00" else 0,
            },
            highlight_function=highlight_function,
            tooltip=tooltip_formatter(row),
        ).add_to(existing_map)

<div class="usecase-body">
    Add a marker cluster so large numbers of residential locations remain readable at different zoom levels.
</div>

In [28]:
def add_marker_cluster(existing_map, data, geometry_column):
    """
    Add residential locations using FastMarkerCluster.

    FastMarkerCluster keeps the same point locations but stores them as one
    compact JavaScript coordinate array instead of embedding a separate
    Folium Marker object for every dwelling. This keeps the saved notebook
    small enough to review on GitHub.
    """
    points = [
        [point.y, point.x]
        for point in data[geometry_column]
        if point is not None and not point.is_empty
    ]

    FastMarkerCluster(points).add_to(existing_map)

<div class="usecase-sub-section-heading">
5.1. Population density
</div>

<div class="usecase-body">
Map population density across SA2 areas to compare where residents are most concentrated.
</div>

In [29]:
# Create a map
Pop_Mel_map = folium.Map(location=[-37.8155, 144.95], tiles='cartodbpositron', min_zoom=11, zoom_start=13)
# Prompt format
def pop_tooltip(row):
    return f'SA2: {row["SA2 name"]}<br>Total Population: {row["Total Population"]}<br>Area km²: {row["Area km2"]}<br>Population Density: {row["Population density 2022 persons/km2"]} per km²'
# Add layer
draw_map(Pop_Mel_map, merged_data, 'Population density 2022 persons/km2', ['#808080', '#059669'], pop_tooltip)

<div class="usecase-body">
Population density is mapped rather than population totals alone because it accounts for differences in area size. This makes it easier to compare how densely populated each SA2 is.
</div>

In [30]:
# Show population density map
Pop_Mel_map

<div class="usecase-body">
Through the layer code, areas with a value of 0 are automatically displayed transparently to avoid visual interference. Areas with no population are industrial areas
</div>

<div class="usecase-sub-section-heading">
5.2. Residential locations
</div>

<div class="usecase-body">
Visualise residential dwelling locations to examine where housing activity is concentrated across the study area.
</div>

In [31]:
# Create a map
Tpop_Mel_map = folium.Map(location=[-37.8155, 144.95], tiles='cartodbpositron', min_zoom=11, zoom_start=13)
# Prompt format
def Tpop_tooltip(row):
    return f'SA2: {row["SA2 name"]}<br>Total Population: {row["Total Population"]}<br>Area km²: {row["Area km2"]}'
# Add layer
draw_map(Tpop_Mel_map, merged_data, 'Total Population', ['#808080', '#9333EA'], Tpop_tooltip)

In [32]:
# add Residential MarkerCluster
add_marker_cluster(Tpop_Mel_map, residential_with_area, 'geometry')

In [33]:
# Show residential map
Tpop_Mel_map

<div class="usecase-body">
The data shows that areas with higher populations tend to have more residential buildings or higher residential density.
</div>

<div class="usecase-sub-section-heading">
5.3. Residential heat map
</div>

<div class="usecase-body">
Display residential dwelling concentrations as a heat map to make broader spatial patterns easier to identify.
</div>

<div class="usecase-body">
Create a regular grid covering the study area for aggregating residential dwelling locations.
</div>

In [34]:
def create_residential_heat_grid(points_gdf, n_side=50):
    """
    Aggregate residential points into a regular grid.

    Every residential record contributes to a grid-cell count, while the
    visualisation stores only one weighted heat point per occupied cell.
    """
    points = points_gdf.to_crs("EPSG:3857").copy()

    xmin, ymin, xmax, ymax = points.total_bounds
    x_edges = np.linspace(xmin, xmax, n_side + 1)
    y_edges = np.linspace(ymin, ymax, n_side + 1)

    # Bin every residential point into a grid cell.
    x_bin = np.clip(
        np.searchsorted(x_edges, points.geometry.x, side="right") - 1,
        0,
        n_side - 1,
    )
    y_bin = np.clip(
        np.searchsorted(y_edges, points.geometry.y, side="right") - 1,
        0,
        n_side - 1,
    )

    counts = (
        pd.DataFrame({"x_bin": x_bin, "y_bin": y_bin})
        .value_counts()
        .rename("dwelling_count")
        .reset_index()
    )

    # Use each occupied cell centre as the heat-map location.
    counts["x"] = (x_edges[counts["x_bin"]] + x_edges[counts["x_bin"] + 1]) / 2
    counts["y"] = (y_edges[counts["y_bin"]] + y_edges[counts["y_bin"] + 1]) / 2

    heat_points = gpd.GeoDataFrame(
        counts,
        geometry=gpd.points_from_xy(counts["x"], counts["y"]),
        crs="EPSG:3857",
    ).to_crs("EPSG:4326")

    return heat_points

In [35]:
# Aggregate all residential records into a 50 × 50 grid.
residential_heat_grid = create_residential_heat_grid(
    residential_with_area[["geometry"]].copy(),
    n_side=50,
)

print(
    f"Residential records represented: {len(residential_with_area):,}\n"
    f"Occupied heat-map cells: {len(residential_heat_grid):,}"
)

Residential records represented: 216,764
Occupied heat-map cells: 624

<div class="usecase-body">
    Extract dwelling coordinates and retain only points that fall within the City of Melbourne boundaries.
</div>

In [36]:
# Validate the aggregated heat-map data.
assert not residential_heat_grid.empty, "No residential heat-map cells were created."
assert residential_heat_grid["dwelling_count"].sum() == len(residential_with_area), (
    "The heat-map aggregation must preserve all residential records."
)

display(residential_heat_grid.head())

,x_bin,y_bin,dwelling_count,x,y,geometry
0,3,37,1920,1.613222e+07,-4.550322e+06,POINT (144.91816 -37.79369)
1,37,33,1753,1.613813e+07,-4.551127e+06,POINT (144.97127 -37.79941)
2,11,34,1729,1.613361e+07,-4.550926e+06,POINT (144.93066 -37.79798)
3,38,36,1691,1.613830e+07,-4.550523e+06,POINT (144.97283 -37.79512)
4,39,36,1665,1.613848e+07,-4.550523e+06,POINT (144.9744 -37.79512)

<div class="usecase-body">
    Calculate the centre of the grid cells so each aggregated value can be displayed on the heat map.
</div>

In [37]:
# The heat-grid points are already stored in WGS 84 (EPSG:4326),
# which Folium expects for latitude and longitude.
assert residential_heat_grid.crs.to_epsg() == 4326

<div class="usecase-body">
    Create a heat-map layer and overlay the City of Melbourne SA2 boundaries for geographic context.
</div>

In [38]:
# Centre the map on the aggregated residential heat-grid.
map_center = [
    residential_heat_grid.geometry.y.mean(),
    residential_heat_grid.geometry.x.mean(),
]

m = folium.Map(
    location=map_center,
    zoom_start=14,
    tiles="cartodbpositron",
)

# One weighted heat point is stored per occupied grid cell rather than one
# point per residential record. All dwelling records are still represented
# through each cell's dwelling_count weight.
heat_data = [
    [point.y, point.x, count]
    for point, count in zip(
        residential_heat_grid.geometry,
        residential_heat_grid["dwelling_count"],
    )
]

HeatMap(
    heat_data,
    radius=30,
    blur=35,
    max_zoom=17,
).add_to(m)

# Overlay SA2 boundaries for geographic context.
for _, area in merged_data_geo.iterrows():
    tooltip = folium.Tooltip(area["SA2 name"])
    folium.GeoJson(
        area["geometry"],
        style_function=lambda feature: {
            "color": "black",
            "weight": 1,
            "fillOpacity": 0,
        },
        highlight_function=highlight_function,
        tooltip=tooltip,
    ).add_to(m)

<div class="usecase-body">
    Display the completed interactive residential heat map.
</div>

In [39]:
folium.LayerControl().add_to(m)
m

<div class="usecase-section-heading">
6. Calculate infrastructure-pressure indicators
</div>

<div class="usecase-body">
Calculate indicators that compare population with available pedestrian infrastructure, public facilities and dining capacity.
</div>

<div class="usecase-sub-section-heading">
6.1. Pedestrian-network pressure
</div>

<div class="usecase-body">
Compare population with pedestrian-network length to estimate pressure on pedestrian infrastructure within each SA2.
</div>

In [40]:
# API URL of the GeoJSON file
ped_geojson_url = "https://data.melbourne.vic.gov.au/api/explore/v2.1/catalog/datasets/pedestrian-network/exports/geojson?lang=en&timezone=Australia%2FSydney"
# Read
ped_gdf = gpd.read_file(ped_geojson_url)
assert not ped_gdf.empty, "The pedestrian network dataset is empty."

In [41]:
# Display
display(ped_gdf)

,geo_point_2d,objectid,neworkid,geometry
0,"{ ""lon"": 144.94163372585001, ""lat"": -37.793721...",65752,None,"LINESTRING (144.94167 -37.79387, 144.94159 -37..."
1,"{ ""lon"": 144.94787215284998, ""lat"": -37.806592...",65790,None,"LINESTRING (144.94779 -37.80653, 144.94795 -37..."
2,"{ ""lon"": 144.92856811765, ""lat"": -37.796488334...",65798,None,"LINESTRING (144.92864 -37.79656, 144.9285 -37...."
3,"{ ""lon"": 144.96138920990001, ""lat"": -37.813115...",65809,None,"LINESTRING (144.96144 -37.81311, 144.96134 -37..."
4,"{ ""lon"": 144.92771797904999, ""lat"": -37.795133...",65860,None,"LINESTRING (144.92767 -37.79508, 144.92777 -37..."
...,...,...,...,...
85321,"{ ""lon"": 144.95180562100001, ""lat"": -37.804308...",9947,106003,POINT (144.95181 -37.80431)
85322,"{ ""lon"": 144.96896124329999, ""lat"": -37.799378...",9952,102727,POINT (144.96896 -37.79938)
85323,"{ ""lon"": 144.9717825411, ""lat"": -37.7959264401...",9968,107588,POINT (144.97178 -37.79593)
85324,"{ ""lon"": 144.95737219329999, ""lat"": -37.796892...",9993,108445,POINT (144.95737 -37.79689)
85325,"{ ""lon"": 144.96165035000001, ""lat"": -37.811909...",10000,103200,POINT (144.96165 -37.81191)

In [42]:
ped_gdf = gpd.GeoDataFrame(ped_gdf, geometry="geometry")
if ped_gdf.crs is None:
    ped_gdf = ped_gdf.set_crs(merged_data_geo.crs)
else:
    ped_gdf = ped_gdf.to_crs(merged_data_geo.crs)

joined = gpd.sjoin(
    ped_gdf,
    merged_data_geo[["SA2 code", "geometry"]],
    how="inner",
    predicate="within",
)

projected_crs = "EPSG:3857"
joined = joined.to_crs(projected_crs)
merged_data_geo = merged_data_geo.to_crs(projected_crs)

<div class="usecase-body">
Calculate the pedestrian-network length within each SA2 and divide population by that length to estimate pressure.
</div>

<div class="usecase-body">

The pedestrian network must be projected into a metric coordinate reference system before measuring line length. Geographic latitude and longitude coordinates are measured in degrees, which are not appropriate for calculating accurate distances in metres.

</div>

In [43]:
joined["street_length"] = joined.geometry.length
street_lengths = joined.groupby("SA2 code")["street_length"].sum()
merged_data_geo["Street_Length"] = (
    merged_data_geo["SA2 code"].map(street_lengths).fillna(0)
)
merged_data_geo["Street_Load"] = np.where(
    merged_data_geo["Street_Length"] > 0,
    merged_data_geo["Total Population"] / merged_data_geo["Street_Length"],
    np.nan,
)

merged_data_geo = merged_data_geo.to_crs(epsg=4326)

In [44]:
# Display
display(merged_data_geo)

,SA2 code,SA2 name,ERP at 30 June 2021 no.,2022 no.,ERP change 2021-22 no.,%,Components of population change 2021-22 Natural increase no.,Net internal migration no.,Net overseas migration no.,Area km2,Population density 2022 persons/km2,Total Population,geometry,Street_Length,Street_Load
0,206041117.0,Carlton,17064.0,18004.0,940.0,5.5,14.0,-610.0,1536.0,1.8,9899.4,17818.92,"POLYGON ((144.97488 -37.79794, 144.97477 -37.7...",144471.536537,0.123339
1,206041118.0,Docklands,15905.0,16456.0,551.0,3.5,179.0,-31.0,403.0,2.4,6733.2,16159.68,"POLYGON ((144.94525 -37.81208, 144.94545 -37.8...",125097.391263,0.129177
2,206041119.0,East Melbourne,4959.0,4884.0,-75.0,-1.5,-10.0,-139.0,74.0,2.9,1684.3,4884.47,"POLYGON ((144.97396 -37.8133, 144.97363 -37.81...",123189.649699,0.039650
3,206041120.0,Flemington Racecourse,78.0,78.0,0.0,0.0,0.0,0.0,0.0,1.7,45.6,77.52,"POLYGON ((144.91598 -37.78187, 144.91698 -37.7...",12958.511845,0.005982
4,206041121.0,Kensington (Vic.),10872.0,11000.0,128.0,1.2,102.0,-114.0,140.0,2.1,5123.4,10759.14,"POLYGON ((144.92172 -37.78987, 144.92243 -37.7...",187451.341478,0.057397
5,206041124.0,Parkville,7428.0,7462.0,34.0,0.5,-8.0,-177.0,219.0,4.0,1842.9,7371.60,"POLYGON ((144.93897 -37.78156, 144.93874 -37.7...",120904.611225,0.060970
6,206041125.0,South Yarra - West,6536.0,6565.0,29.0,0.4,4.0,-70.0,95.0,1.5,4368.8,6553.20,"POLYGON ((144.97455 -37.83467, 144.97445 -37.8...",72500.315628,0.090389
7,206041127.0,West Melbourne - Industrial,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6.2,0.0,0.00,"POLYGON ((144.90759 -37.80612, 144.90769 -37.8...",61050.472189,0.000000
8,206041503.0,Melbourne CBD - East,10119.0,10655.0,536.0,5.3,34.0,-74.0,576.0,0.8,13285.5,10628.40,"POLYGON ((144.96534 -37.81137, 144.96576 -37.8...",81896.039240,0.129779
9,206041504.0,Melbourne CBD - North,17360.0,18826.0,1466.0,8.4,57.0,482.0,927.0,0.6,33522.1,20113.26,"POLYGON ((144.95569 -37.80771, 144.95599 -37.8...",66087.268954,0.304344
10,206041505.0,Melbourne CBD - West,16098.0,17299.0,1201.0,7.5,71.0,333.0,797.0,1.0,17211.2,17211.20,"POLYGON ((144.9528 -37.8161, 144.95235 -37.815...",79162.918347,0.217415
11,206041506.0,North Melbourne,15945.0,16582.0,637.0,4.0,64.0,-131.0,704.0,2.4,6838.5,16412.40,"POLYGON ((144.93585 -37.79507, 144.93569 -37.7...",182412.665533,0.089974
12,206041507.0,Royal Botanic Gardens Victoria,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.4,0.0,0.00,"POLYGON ((144.97665 -37.82318, 144.97743 -37.8...",39737.934821,0.000000
13,206041508.0,Southbank (West) - South Wharf,6607.0,6814.0,207.0,3.1,31.0,15.0,161.0,0.8,8020.2,6416.16,"POLYGON ((144.96478 -37.8197, 144.96539 -37.81...",30938.933523,0.207381
14,206041509.0,Southbank - East,16506.0,17340.0,834.0,5.1,134.0,315.0,385.0,0.8,21567.2,17253.76,"POLYGON ((144.96589 -37.8218, 144.96622 -37.82...",40800.505099,0.422881
15,206041510.0,West Melbourne - Residential,7614.0,8014.0,400.0,5.3,46.0,169.0,185.0,0.8,9717.5,7774.00,"POLYGON ((144.94264 -37.80731, 144.94285 -37.8...",63791.209486,0.121866

<div class="usecase-body">
    Visualise the calculated indicator on an interactive choropleth map.
</div>

In [45]:
# Create a map
Ped_Mel_map = folium.Map(location=[-37.8155, 144.95], tiles='cartodbpositron', min_zoom=11, zoom_start=13)
# Prompt format
def ped_tooltip(row):
    return f'SA2: {row["SA2 name"]}<br>Total Population: {row["Total Population"]}<br>Street Load: {row["Street_Load"]}'
# Add layer
draw_map(Ped_Mel_map, merged_data_geo, 'Street_Load', ['#808080', '#F97316'], ped_tooltip)

In [46]:
# Show regional sidewalk capacity map
Ped_Mel_map

<div class="usecase-body">
    The city-centre SA2 areas show the greatest estimated pressure on the pedestrian network.
</div>

<div class="usecase-sub-section-heading">
6.2. Public-facility pressure
</div>

<div class="usecase-body">
Compare population with available public facilities to estimate facility pressure within each SA2.
</div>

In [47]:
# API URL of the GeoJSON file
lan_geojson_url = "https://data.melbourne.vic.gov.au/api/explore/v2.1/catalog/datasets/landmarks-and-places-of-interest-including-schools-theatres-health-services-spor/exports/geojson?lang=en&timezone=Australia%2FSydney"

# Read
Land_gdf = gpd.read_file(lan_geojson_url)
assert not Land_gdf.empty, "The landmarks dataset is empty."

In [48]:
# Display
display(Land_gdf)

,theme,sub_theme,feature_name,geometry
0,Leisure/Recreation,Major Sports & Recreation Facility,Carlton Football Club,POINT (144.96197 -37.78409)
1,Education Centre,Primary Schools,Carlton Gardens Primary School,POINT (144.96941 -37.8021)
2,Leisure/Recreation,Informal Outdoor Facility (Park/Garden/Reserve),Kings Domain,POINT (144.97411 -37.82552)
3,Education Centre,Secondary Schools,Melbourne Grammar School,POINT (144.97629 -37.83426)
4,Mixed Use,Retail/Office/Carpark,Southgate Arts and Leisure Precinct,POINT (144.96599 -37.82022)
...,...,...,...,...
237,Transport,Railway Station,Melbourne Central Railway Station,POINT (144.96267 -37.80978)
238,Place Of Assembly,Art Gallery/Museum,Victoria Police Museum,POINT (144.95404 -37.82222)
239,Place of Worship,Church,St Pauls Cathedral,POINT (144.96768 -37.81695)
240,Community Use,Visitor Centre,Melbourne Visitor Centre,POINT (144.96794 -37.81774)
241,Place Of Assembly,Art Gallery/Museum,Australian Centre For The Moving Image (ACMI),POINT (144.96907 -37.81761)

<div class="usecase-body">
Remove facilities outside the study area, count facilities within each SA2 and calculate population per facility.
</div>

In [49]:
Land_gdf = Land_gdf.to_crs(merged_data_geo.crs)
landmarks_within_lga = gpd.sjoin(
    Land_gdf,
    merged_data_geo[["SA2 code", "geometry"]],
    how="inner",
    predicate="within",
)

landmark_counts = landmarks_within_lga.groupby("SA2 code").size()
merged_data_geo["landmark_count"] = (
    merged_data_geo["SA2 code"].map(landmark_counts).fillna(0).astype(int)
)
merged_data_geo["landmark_load"] = np.where(
    merged_data_geo["landmark_count"] > 0,
    merged_data_geo["Total Population"] / merged_data_geo["landmark_count"],
    np.nan,
)

<div class="usecase-body">
    Visualise the calculated indicator on an interactive choropleth map.
</div>

In [50]:
# Create a map
Land_Mel_map = folium.Map(location=[-37.8155, 144.95], tiles='cartodbpositron', min_zoom=11, zoom_start=13)
# Prompt format
def Land_tooltip(row):
    return f'SA2: {row["SA2 name"]}<br>Landmark Count: {row["landmark_count"]}<br>Landmark Load: {row["landmark_load"]}'
# Add layer
draw_map(Land_Mel_map, merged_data_geo, 'landmark_load', ['#808080', '#2563EB'], Land_tooltip)

In [51]:
# Display regional public facility capacity map
Land_Mel_map

<div class="usecase-body">
    The city-centre SA2 areas show the greatest estimated pressure on mapped public facilities.
</div>

<div class="usecase-sub-section-heading">
6.3. Dining-seat pressure
</div>

<div class="usecase-body">
Compare population with café and restaurant seating capacity to estimate dining-seat pressure within each SA2.
</div>

In [52]:
# API URL of the GeoJSON file
Caf_geojson_url = "https://data.melbourne.vic.gov.au/api/explore/v2.1/catalog/datasets/cafes-and-restaurants-with-seating-capacity/exports/geojson?lang=en&timezone=Australia%2FSydney"

# Read
Caf_gdf = gpd.read_file(Caf_geojson_url)
assert not Caf_gdf.empty, "The café and restaurant dataset is empty."

In [53]:
# Display
display(Caf_gdf)

,census_year,block_id,property_id,base_property_id,building_address,clue_small_area,trading_name,business_address,industry_anzsic4_code,industry_anzsic4_description,seating_type,number_of_seats,longitude,latitude,location,geometry
0,2007,13,110151,110151,22-38 William Street MELBOURNE 3000,Melbourne (CBD),Cafe 22,"Part Ground , 22 William Street MELBOURNE 3000",4511,Cafes and Restaurants,Seats - Indoor,75,144.959975,-37.818778,None,POINT (144.95997 -37.81878)
1,2007,14,103166,103166,7-9 Elizabeth Street MELBOURNE 3000,Melbourne (CBD),Pepperoni's,7A Elizabeth Street MELBOURNE 3000,4511,Cafes and Restaurants,Seats - Indoor,70,144.964560,-37.817933,None,POINT (144.96456 -37.81793)
2,2007,14,103167,103167,11-15 Elizabeth Street MELBOURNE 3000,Melbourne (CBD),McDonald's,11-15 Elizabeth Street MELBOURNE 3000,4511,Cafes and Restaurants,Seats - Outdoor,12,144.964509,-37.817831,None,POINT (144.96451 -37.81783)
3,2007,14,104004,104004,342-348 Flinders Street MELBOURNE 3000,Melbourne (CBD),Aria Cafe,"Part Ground , 342-348 Flinders Street MELBOURN...",4511,Cafes and Restaurants,Seats - Indoor,30,144.963086,-37.818453,None,POINT (144.96309 -37.81845)
4,2007,14,104008,104008,292-298 Flinders Street MELBOURNE 3000,Melbourne (CBD),Vita Juice Energy For Life,298 Flinders Street MELBOURNE 3000,4512,Takeaway Food Services,Seats - Indoor,11,144.964363,-37.818076,None,POINT (144.96436 -37.81808)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
66351,2007,12,103999,103999,1-13 William Street MELBOURNE 3000,Melbourne (CBD),Williams Bar Cafe,"Restaurant , 1 William Street MELBOURNE 3000",4511,Cafes and Restaurants,Seats - Outdoor,16,144.959520,-37.819434,None,POINT (144.95952 -37.81943)
66352,2007,12,105402,105402,8-10 King Street MELBOURNE 3000,Melbourne (CBD),Monkey Bar Noodles & Sushi,10 King Street MELBOURNE 3000,4511,Cafes and Restaurants,Seats - Indoor,30,144.957647,-37.819929,None,POINT (144.95765 -37.81993)
66353,2007,12,110091,110091,15-33 William Street MELBOURNE 3000,Melbourne (CBD),Hotel Food Drink,"Part Ground 0, 15-33 William Street MELBOURNE ...",4511,Cafes and Restaurants,Seats - Indoor,130,144.959197,-37.819217,None,POINT (144.9592 -37.81922)
66354,2007,13,104002,104002,376-388 Flinders Street MELBOURNE 3000,Melbourne (CBD),Gosh Cafe,"Shop 1, Ground , 376 Flinders Street MELBOURNE...",4512,Takeaway Food Services,Seats - Indoor,30,144.961539,-37.818848,None,POINT (144.96154 -37.81885)
66355,2007,13,106438,106438,14-40 Market Street MELBOURNE 3000,Melbourne (CBD),Koury's Coffee Lounge,"Part Ground , 389 Market Street MELBOURNE 3000",4511,Cafes and Restaurants,Seats - Indoor,43,144.961143,-37.818489,None,POINT (144.96114 -37.81849)

<div class="usecase-body">
    Remove dining records outside the study area, sum seating capacity within each SA2 and calculate population per seat.
</div>

In [54]:
Caf_gdf = Caf_gdf.to_crs(merged_data_geo.crs)
cafes_within_lga = gpd.sjoin(
    Caf_gdf,
    merged_data_geo[["SA2 code", "geometry"]],
    how="inner",
    predicate="within",
)

seat_totals = cafes_within_lga.groupby("SA2 code")["number_of_seats"].sum()
merged_data_geo["total_seats"] = (
    merged_data_geo["SA2 code"].map(seat_totals).fillna(0)
)
merged_data_geo["seat_load"] = np.where(
    merged_data_geo["total_seats"] > 0,
    merged_data_geo["Total Population"] / merged_data_geo["total_seats"],
    np.nan,
)

<div class="usecase-body">Visualise the calculated indicator on an interactive choropleth map.</div>

In [55]:
# Create a map
Caf_Mel_map = folium.Map(location=[-37.8155, 144.95], tiles='cartodbpositron', min_zoom=11, zoom_start=13)
# Prompt format
def Caf_tooltip(row):
    return f'SA2: {row["SA2 name"]}<br>Total Seats: {row["total_seats"]}<br>Seat Load: {row["seat_load"]}'
# Add layer
draw_map(Caf_Mel_map, merged_data_geo, 'seat_load', ['#808080', '#EAB308'], Caf_tooltip)

In [56]:
# Display dining seating capacity map
Caf_Mel_map

<div class="usecase-body">Some populated areas have limited mapped dining capacity, which lowers their relative convenience score.</div>

<div class="usecase-section-heading">
7. Calculate and validate the liveability score
</div>

<div class="usecase-body">
Normalise the infrastructure-pressure indicators and combine them into an exploratory liveability score for eligible residential areas.
</div>

In [57]:
pressure_columns = ["Street_Load", "landmark_load", "seat_load"]
normalised_columns = [
    "Street_Load_norm", "landmark_load_norm", "seat_load_norm"
]

residential_counts = residential_with_area.groupby("CLUE small area").size()
merged_data_geo["residential_record_count"] = (
    merged_data_geo["SA2 name"].map(residential_counts).fillna(0).astype(int)
)

eligible_mask = (
    merged_data_geo["Total Population"].gt(0)
    & merged_data_geo["residential_record_count"].gt(0)
)

merged_data_geo[normalised_columns] = np.nan
eligible_pressure = merged_data_geo.loc[eligible_mask, pressure_columns].copy()

# A missing pressure value means that no mapped capacity was available.
# Replace it with a value slightly above the largest observed pressure so it
# receives the lowest normalised component score.
for column in pressure_columns:
    observed_max = eligible_pressure[column].replace([np.inf, -np.inf], np.nan).max()
    fallback = observed_max * 1.05 if pd.notna(observed_max) and observed_max > 0 else 1.0
    eligible_pressure[column] = (
        eligible_pressure[column].replace([np.inf, -np.inf], np.nan).fillna(fallback)
    )

scaler = MinMaxScaler()
normalised_values = 1 - scaler.fit_transform(eligible_pressure)
merged_data_geo.loc[eligible_mask, normalised_columns] = normalised_values

weights = np.array([1 / 3, 1 / 3, 1 / 3])
merged_data_geo["liveability_score"] = np.nan
merged_data_geo.loc[eligible_mask, "liveability_score"] = (
    merged_data_geo.loc[eligible_mask, normalised_columns].to_numpy() @ weights
)

In [58]:
# Display
display(merged_data_geo)

,SA2 code,SA2 name,ERP at 30 June 2021 no.,2022 no.,ERP change 2021-22 no.,%,Components of population change 2021-22 Natural increase no.,Net internal migration no.,Net overseas migration no.,Area km2,...,Street_Load,landmark_count,landmark_load,total_seats,seat_load,residential_record_count,Street_Load_norm,landmark_load_norm,seat_load_norm,liveability_score
0,206041117.0,Carlton,17064.0,18004.0,940.0,5.5,14.0,-610.0,1536.0,1.8,...,0.123339,20,890.946000,353725,0.050375,36342,0.718501,0.661127,0.887015,0.755548
1,206041118.0,Docklands,15905.0,16456.0,551.0,3.5,179.0,-31.0,403.0,2.4,...,0.129177,21,769.508571,364787,0.044299,2167,0.704498,0.708343,0.900880,0.771240
2,206041119.0,East Melbourne,4959.0,4884.0,-75.0,-1.5,-10.0,-139.0,74.0,2.9,...,0.039650,48,101.759792,320030,0.015263,16013,0.919242,0.967970,0.967135,0.951449
3,206041120.0,Flemington Racecourse,78.0,78.0,0.0,0.0,0.0,0.0,0.0,1.7,...,0.005982,4,19.380000,90225,0.000859,44,1.000000,1.000000,1.000000,1.000000
4,206041121.0,Kensington (Vic.),10872.0,11000.0,128.0,1.2,102.0,-114.0,140.0,2.1,...,0.057397,7,1537.020000,24502,0.439113,61099,0.876673,0.409927,0.000000,0.428867
5,206041124.0,Parkville,7428.0,7462.0,34.0,0.5,-8.0,-177.0,219.0,4.0,...,0.060970,13,567.046154,71278,0.103420,15733,0.868102,0.787062,0.765977,0.807047
6,206041125.0,South Yarra - West,6536.0,6565.0,29.0,0.4,4.0,-70.0,95.0,1.5,...,0.090389,9,728.133333,76722,0.085415,17733,0.797537,0.724430,0.807062,0.776343
7,206041127.0,West Melbourne - Industrial,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6.2,...,0.000000,5,0.000000,6390,0.000000,3,NaN,NaN,NaN,NaN
8,206041503.0,Melbourne CBD - East,10119.0,10655.0,536.0,5.3,34.0,-74.0,576.0,0.8,...,0.129779,21,506.114286,940175,0.011305,3293,0.703053,0.810753,0.976166,0.829990
9,206041504.0,Melbourne CBD - North,17360.0,18826.0,1466.0,8.4,57.0,482.0,927.0,0.6,...,0.304344,14,1436.661429,300219,0.066995,1625,0.284331,0.448947,0.849092,0.527457
10,206041505.0,Melbourne CBD - West,16098.0,17299.0,1201.0,7.5,71.0,333.0,797.0,1.0,...,0.217415,15,1147.413333,645680,0.026656,2327,0.492844,0.561410,0.941137,0.665130
11,206041506.0,North Melbourne,15945.0,16582.0,637.0,4.0,64.0,-131.0,704.0,2.4,...,0.089974,14,1172.314286,113982,0.143991,44927,0.798532,0.551728,0.673404,0.674555
12,206041507.0,Royal Botanic Gardens Victoria,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.4,...,0.000000,9,0.000000,15791,0.000000,45,NaN,NaN,NaN,NaN
13,206041508.0,Southbank (West) - South Wharf,6607.0,6814.0,207.0,3.1,31.0,15.0,161.0,0.8,...,0.207381,12,534.680000,298527,0.021493,353,0.516911,0.799646,0.952919,0.756492
14,206041509.0,Southbank - East,16506.0,17340.0,834.0,5.1,134.0,315.0,385.0,0.8,...,0.422881,17,1014.927059,58735,0.293756,962,0.000000,0.612922,0.331673,0.314865
15,206041510.0,West Melbourne - Residential,7614.0,8014.0,400.0,5.3,46.0,169.0,185.0,0.8,...,0.121866,3,2591.333333,61656,0.126087,14098,0.722033,0.000000,0.714258,0.478764

<div class="usecase-sub-section-heading">
7.1. Validation checks
</div>

<div class="usecase-body">
Validate the calculated liveability scores and confirm that excluded areas are handled correctly.
</div>

In [59]:
eligible_scores = merged_data_geo.loc[eligible_mask, "liveability_score"]
excluded_scores = merged_data_geo.loc[~eligible_mask, "liveability_score"]

assert eligible_scores.between(0, 1).all(), "Eligible scores must be between 0 and 1."
assert excluded_scores.isna().all(), "Excluded areas must not receive a score."
assert merged_data_geo.geometry.notna().all(), "All scored records require geometry."

print(f"Eligible residential areas: {eligible_mask.sum()}")
print(f"Excluded non-residential areas: {(~eligible_mask).sum()}")
print(f"Score range: {eligible_scores.min():.3f} to {eligible_scores.max():.3f}")

top_areas = (
    merged_data_geo.loc[eligible_mask, ["SA2 name", "liveability_score"]]
    .sort_values("liveability_score", ascending=False)
    .head(5)
)
display(top_areas)

Eligible residential areas: 14
Excluded non-residential areas: 2
Score range: 0.315 to 1.000

                SA2 name  liveability_score
3  Flemington Racecourse           1.000000
2         East Melbourne           0.951449
8   Melbourne CBD - East           0.829990
5              Parkville           0.807047
6     South Yarra - West           0.776343

<div class="usecase-body">Visualise the calculated indicator on an interactive choropleth map.</div>

In [60]:
# Create a map
Liv_Mel_map = folium.Map(location=[-37.8155, 144.95], tiles='cartodbpositron', min_zoom=11, zoom_start=13)
# Prompt format
def Liv_tooltip(row):
    return f'SA2: {row["SA2 name"]}<br>Liveability Score: {row["liveability_score"]}'
# Add layer
draw_map(Liv_Mel_map, merged_data_geo, 'liveability_score', ['#EC4899', '#EAB308', '#059669'], Liv_tooltip)

In [61]:
# Show residential comfort map
Liv_Mel_map

<div class="usecase-body">
The final map uses pink for lower scores, yellow for moderate scores and green for higher scores. Transparent polygons represent areas excluded from the residential comparison because they have no population or no residential dwelling records. The score should be interpreted as an exploratory comparison based only on the three indicators included in this use case.
</div>

<div id="conclusion" class="usecase-unnumbered-heading"><b>Conclusion</b></div>

<div class="usecase-body">

<b>What we achieved in this analysis</b>

<p>
This analysis brought together population, housing and local infrastructure data to build a clearer picture of liveability across different areas of Melbourne. By comparing these factors across residential areas, the analysis helps identify differences in living conditions and areas experiencing greater pressure on available infrastructure.
</p>

<p>
For present or prospective residents, the results provide a way to compare areas based on factors that may contribute to a comfortable living environment. For City of Melbourne planners, the analysis can help highlight areas where population and residential activity place greater pressure on pedestrian infrastructure, public facilities and dining capacity, supporting more informed decisions about where future planning and investment may be needed.
</p>

<b>What we learned from this analysis</b>

<p>
The use case shows us how different public datasets can be prepared, combined and visualised to answer practical questions about urban liveability. It also demonstrates the use of geospatial data preparation, spatial joins, coordinate reference systems, interactive mapping and the creation of comparable liveability indicators across SA2 areas.
</p>

<p>
The results should be interpreted as an indication of liveability based on the factors included in this analysis rather than a complete measure of how desirable an area is. Liveability can depend on many additional factors and individual priorities that are not represented in these datasets.
</p>

<b>Observations for further opportunities</b>

<p>
Future analysis could provide a more complete view of liveability by including factors such as public transport access, green space, housing affordability, safety and healthcare access. Different indicator weightings could also be explored to reflect the different priorities of residents and urban planners. Keeping the datasets current and reviewing their completeness would further improve the usefulness of the analysis for future planning decisions.
</p>

</div>