In [31]:
import pandas as pd
import requests


def load_melbourne_api(dataset_slug, rows=5000):
    url = "https://data.melbourne.vic.gov.au/api/records/1.0/search/"

    params = {
        "dataset": dataset_slug,
        "rows": rows
    }

    response = requests.get(url, params=params)
    response.raise_for_status()

    data = response.json()
    records = data.get("records", [])

    return pd.DataFrame([record["fields"] for record in records])


on_street_parking_bay_sensor_df = load_melbourne_api(
    "on-street-parking-bay-sensors",
    rows=5000
)

sign_plates_located_in_parking_bays_df = load_melbourne_api(
    "sign-plates-located-in-each-parking-zone",
    rows=5000
)

on_street_car_parking_sensor_df = pd.read_csv("../data/raw/On-street_Car_Parking_Sensor_Data_-_2014.csv",nrows=300000)
parking_bay_arrivals_and_departures_df = pd.read_csv("../data/raw/Parking_bay_arrivals_and_departures_2014.csv",nrows=300000)

/tmp/ipykernel_31094/912495490.py:33: DtypeWarning: Columns (0: StreetId, 1: BetweenStreet1 Id, 2: BetweenStreet2 Id) have mixed types. Specify dtype option on import or set low_memory=False.
  parking_bay_arrivals_and_departures_df = pd.read_csv("../data/raw/Parking_bay_arrivals_and_departures_2014.csv",nrows=300000)

In [32]:
print("**on_street_car_parking_sensor_df**")
print(on_street_car_parking_sensor_df.head())
print(on_street_car_parking_sensor_df.columns)
on_street_car_parking_sensor_df.info()

**on_street_car_parking_sensor_df**
  DeviceId             ArrivalTime           DepartureTime DurationSeconds StreetMarker                       Sign            Area  \
0   10,032  07/01/2014 11:43:23 AM  07/01/2014 11:43:30 AM               7        3273S      1P MTR M-F 9:30-19:30          County
1   11,649  03/19/2014 10:09:38 AM  03/19/2014 10:11:22 AM             104        2206N  1/2P MTR M-SAT 7:30-19:30        McKillop
2    9,126  06/12/2014 07:30:00 AM  06/12/2014 10:17:23 AM          10,043       11921W      2P MTR M-F 7:30-18:30  East Melbourne
3   12,462  07/02/2014 07:30:11 AM  07/02/2014 07:34:11 AM             240        2418N       1/4P M-SAT 7:30-9:30            RACV
4   14,588  07/16/2014 08:12:00 AM  07/16/2014 08:12:14 AM              14       13749W  2P TKT A M-SAT 7:30-18:30       Docklands

  StreetId         StreetName   BetweenStreet1      BetweenStreet2  Side Of Street  In Violation  Vehicle Present
0      894    LONSDALE STREET      KING STREET      WILLIAM STREET             4.0         False            False
1      911  Lt COLLINS STREET     QUEEN STREET    ELIZABETH STREET             3.0         False            False
2      511   CLARENDON STREET    GEORGE STREET   WELLINGTON PARADE             5.0         False            False
3      123      BOURKE STREET   WILLIAM STREET        QUEEN STREET             3.0         False             True
4    1,398     WATERFRONT WAY  DOCKLANDS DRIVE  Lt DOCKLANDS DRIVE             5.0         False            False
Index(['DeviceId', 'ArrivalTime', 'DepartureTime', 'DurationSeconds', 'StreetMarker', 'Sign', 'Area', 'StreetId', 'StreetName',
       'BetweenStreet1', 'BetweenStreet2', 'Side Of Street', 'In Violation', 'Vehicle Present'],
      dtype='str')
<class 'pandas.DataFrame'>
RangeIndex: 300000 entries, 0 to 299999
Data columns (total 14 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   DeviceId         300000 non-null  str
 1   ArrivalTime      300000 non-null  str
 2   DepartureTime    300000 non-null  str
 3   DurationSeconds  300000 non-null  str
 4   StreetMarker     299981 non-null  str
 5   Sign             288775 non-null  str
 6   Area             299981 non-null  str
 7   StreetId         299981 non-null  str
 8   StreetName       299981 non-null  str
 9   BetweenStreet1   299981 non-null  str
 10  BetweenStreet2   299697 non-null  str
 11  Side Of Street   299981 non-null  float64
 12  In Violation     300000 non-null  bool
 13  Vehicle Present  300000 non-null  bool
dtypes: bool(2), float64(1), str(11)
memory usage: 28.0 MB

In [33]:
print("**on_street_parking_bay_sensor_df**")
print(on_street_parking_bay_sensor_df.head())
print(on_street_parking_bay_sensor_df.columns)
on_street_parking_bay_sensor_df.info()

**on_street_parking_bay_sensor_df**
            status_timestamp  zone_number                lastupdated  kerbsideid status_description  \
0  2024-08-18T08:23:46+00:00       7394.0  2024-12-30T00:44:37+00:00        9344         Unoccupied
1  2024-08-14T09:22:05+00:00       7392.0  2025-01-10T02:44:36+00:00        9373         Unoccupied
2  2024-11-28T02:30:57+00:00       7084.0  2024-12-04T23:44:37+00:00        8735            Present
3  2024-11-27T23:23:40+00:00       7084.0  2024-12-04T23:44:37+00:00        8749         Unoccupied
4  2023-08-21T00:09:03+00:00       7800.0  2025-01-09T05:44:36+00:00       24505            Present

                                   location
0  [-37.80494402936792, 144.95916129121264]
1  [-37.80329074425858, 144.95836336946644]
2  [-37.80223335664963, 144.96120480793184]
3   [-37.80230361629087, 144.9618505999636]
4  [-37.79756250415984, 144.95759881813447]
Index(['status_timestamp', 'zone_number', 'lastupdated', 'kerbsideid', 'status_description', 'location'], dtype='str')
<class 'pandas.DataFrame'>
RangeIndex: 3309 entries, 0 to 3308
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   status_timestamp    3309 non-null   str
 1   zone_number         3091 non-null   float64
 2   lastupdated         3309 non-null   str
 3   kerbsideid          3309 non-null   int64
 4   status_description  3309 non-null   str
 5   location            3309 non-null   object
dtypes: float64(1), int64(1), object(1), str(3)
memory usage: 155.2+ KB

In [34]:
print("**parking_bay_arrivals_and_departures_df**")
print(parking_bay_arrivals_and_departures_df.head())
print(parking_bay_arrivals_and_departures_df.columns)
parking_bay_arrivals_and_departures_df.info()

**parking_bay_arrivals_and_departures_df**
  ParkingEventId DeviceId                   ArrivalTime                 DepartureTime DurationSeconds StreetMarker  SignPlateId  \
0          3,123   11,710  04/02/2014 10:56:29 AM +0000  04/02/2014 11:06:08 AM +0000             600        6588N            6
1          3,124   11,710  04/02/2014 11:07:23 AM +0000  04/02/2014 11:38:48 AM +0000           1,860        6588N            6
2          3,125   11,710  04/02/2014 12:09:59 PM +0000  04/02/2014 12:34:30 PM +0000           1,500        6588N            6
3          3,126   11,710  04/02/2014 12:39:30 PM +0000  04/02/2014 12:58:07 PM +0000           1,140        6588N            6
4          3,129   11,710  04/02/2014 01:08:46 PM +0000  04/02/2014 01:14:46 PM +0000             360        6588N            6

                      Sign  Area         AreaName StreetId       StreetName BetweenStreet1 Id BetweenStreet1 Description  \
0  1P MTR M-SAT 7:30-19:30    12  Victoria Market      681  FRANKLIN STREET             1,171               QUEEN STREET
1  1P MTR M-SAT 7:30-19:30    12  Victoria Market      681  FRANKLIN STREET             1,171               QUEEN STREET
2  1P MTR M-SAT 7:30-19:30    12  Victoria Market      681  FRANKLIN STREET             1,171               QUEEN STREET
3  1P MTR M-SAT 7:30-19:30    12  Victoria Market      681  FRANKLIN STREET             1,171               QUEEN STREET
4  1P MTR M-SAT 7:30-19:30    12  Victoria Market      681  FRANKLIN STREET             1,171               QUEEN STREET

  BetweenStreet2 Id BetweenStreet2 Description  SideOfStreet SideCode SideName  BayID  InViolation
0               627           ELIZABETH STREET             3        N    North  3,495        False
1               627           ELIZABETH STREET             3        N    North  3,495        False
2               627           ELIZABETH STREET             3        N    North  3,495        False
3               627           ELIZABETH STREET             3        N    North  3,495        False
4               627           ELIZABETH STREET             3        N    North  3,495        False
Index(['ParkingEventId', 'DeviceId', 'ArrivalTime', 'DepartureTime', 'DurationSeconds', 'StreetMarker', 'SignPlateId', 'Sign', 'Area',
       'AreaName', 'StreetId', 'StreetName', 'BetweenStreet1 Id', 'BetweenStreet1 Description', 'BetweenStreet2 Id',
       'BetweenStreet2 Description', 'SideOfStreet', 'SideCode', 'SideName', 'BayID', 'InViolation'],
      dtype='str')
<class 'pandas.DataFrame'>
RangeIndex: 300000 entries, 0 to 299999
Data columns (total 21 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   ParkingEventId              300000 non-null  str
 1   DeviceId                    300000 non-null  str
 2   ArrivalTime                 300000 non-null  str
 3   DepartureTime               300000 non-null  str
 4   DurationSeconds             300000 non-null  str
 5   StreetMarker                300000 non-null  str
 6   SignPlateId                 300000 non-null  int64
 7   Sign                        281953 non-null  str
 8   Area                        300000 non-null  int64
 9   AreaName                    300000 non-null  str
 10  StreetId                    300000 non-null  object
 11  StreetName                  300000 non-null  str
 12  BetweenStreet1 Id           300000 non-null  object
 13  BetweenStreet1 Description  300000 non-null  str
 14  BetweenStreet2 Id           300000 non-null  object
 15  BetweenStreet2 Description  300000 non-null  str
 16  SideOfStreet                300000 non-null  int64
 17  SideCode                    300000 non-null  str
 18  SideName                    300000 non-null  str
 19  BayID                       300000 non-null  str
 20  InViolation                 300000 non-null  bool
dtypes: bool(1), int64(3), object(3), str(14)
memory usage: 46.1+ MB

In [35]:
print("**sign_plates_located_in_parking_bays_df**")
print(sign_plates_located_in_parking_bays_df.head())
print(sign_plates_located_in_parking_bays_df.columns)
sign_plates_located_in_parking_bays_df.info()

**sign_plates_located_in_parking_bays_df**
  restriction_display  parkingzone time_restrictions_start restriction_days time_restrictions_finish
0                  2P         7001                07:30:00              Sat                 12:30:00
1                  2P         7007                07:30:00              Sat                 12:30:00
2                  2P         7025                07:30:00          Mon-Fri                 18:30:00
3                  2P         7025                07:30:00              Sat                 12:30:00
4                  HP         7019                07:30:00              Sat                 12:30:00
Index(['restriction_display', 'parkingzone', 'time_restrictions_start', 'restriction_days', 'time_restrictions_finish'], dtype='str')
<class 'pandas.DataFrame'>
RangeIndex: 2033 entries, 0 to 2032
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   restriction_display       2033 non-null   str
 1   parkingzone               2033 non-null   int64
 2   time_restrictions_start   2033 non-null   str
 3   restriction_days          2033 non-null   str
 4   time_restrictions_finish  2033 non-null   str
dtypes: int64(1), str(4)
memory usage: 79.5 KB

In [36]:
def clean_column_names(df):
    df = df.copy()
    df.columns = (
        df.columns.str.strip()
        .str.lower()
        .str.replace(" ", "_")
        .str.replace("-", "_")
    )
    return df

on_street_car_parking_sensor_df = clean_column_names(on_street_car_parking_sensor_df)
on_street_parking_bay_sensor_df = clean_column_names(on_street_parking_bay_sensor_df)
parking_bay_arrivals_and_departures_df = clean_column_names(parking_bay_arrivals_and_departures_df)
sign_plates_located_in_parking_bays_df = clean_column_names(sign_plates_located_in_parking_bays_df)

In [37]:
print("on_street_car_parking_sensor_df columns:")
print(on_street_car_parking_sensor_df.columns.tolist())

print("\non_street_parking_bay_sensor_df columns:")
print(on_street_parking_bay_sensor_df.columns.tolist())

print("\nparking_bay_arrivals_and_departures_df columns:")
print(parking_bay_arrivals_and_departures_df.columns.tolist())

print("\nsign_plates_located_in_parking_bays_df columns:")
print(sign_plates_located_in_parking_bays_df.columns.tolist())

on_street_car_parking_sensor_df columns:
['deviceid', 'arrivaltime', 'departuretime', 'durationseconds', 'streetmarker', 'sign', 'area', 'streetid', 'streetname', 'betweenstreet1', 'betweenstreet2', 'side_of_street', 'in_violation', 'vehicle_present']

on_street_parking_bay_sensor_df columns:
['status_timestamp', 'zone_number', 'lastupdated', 'kerbsideid', 'status_description', 'location']

parking_bay_arrivals_and_departures_df columns:
['parkingeventid', 'deviceid', 'arrivaltime', 'departuretime', 'durationseconds', 'streetmarker', 'signplateid', 'sign', 'area', 'areaname', 'streetid', 'streetname', 'betweenstreet1_id', 'betweenstreet1_description', 'betweenstreet2_id', 'betweenstreet2_description', 'sideofstreet', 'sidecode', 'sidename', 'bayid', 'inviolation']

sign_plates_located_in_parking_bays_df columns:
['restriction_display', 'parkingzone', 'time_restrictions_start', 'restriction_days', 'time_restrictions_finish']

In [38]:
on_street_car_parking_sensor_df = on_street_car_parking_sensor_df.drop_duplicates()
on_street_parking_bay_sensor_df["location"] = (
    on_street_parking_bay_sensor_df["location"].apply(
        lambda value: tuple(value) if isinstance(value, list) else value
    )
)
on_street_parking_bay_sensor_df = on_street_parking_bay_sensor_df.drop_duplicates()
parking_bay_arrivals_and_departures_df = parking_bay_arrivals_and_departures_df.drop_duplicates()
sign_plates_located_in_parking_bays_df = sign_plates_located_in_parking_bays_df.drop_duplicates()

In [39]:
# For 2014 sensor data
on_street_car_parking_sensor_df["deviceid"] = (
    on_street_car_parking_sensor_df["deviceid"].astype(str).str.replace(",", "", regex=False)
)
on_street_car_parking_sensor_df["streetid"] = (
    on_street_car_parking_sensor_df["streetid"].astype(str).str.replace(",", "", regex=False)
)
on_street_car_parking_sensor_df["durationseconds"] = (
    on_street_car_parking_sensor_df["durationseconds"].astype(str).str.replace(",", "", regex=False)
)

# For arrivals/departures data
parking_bay_arrivals_and_departures_df["parkingeventid"] = (
    parking_bay_arrivals_and_departures_df["parkingeventid"].astype(str).str.replace(",", "", regex=False)
)
parking_bay_arrivals_and_departures_df["deviceid"] = (
    parking_bay_arrivals_and_departures_df["deviceid"].astype(str).str.replace(",", "", regex=False)
)
parking_bay_arrivals_and_departures_df["durationseconds"] = (
    parking_bay_arrivals_and_departures_df["durationseconds"].astype(str).str.replace(",", "", regex=False)
)
parking_bay_arrivals_and_departures_df["bayid"] = (
    parking_bay_arrivals_and_departures_df["bayid"].astype(str).str.replace(",", "", regex=False)
)

In [40]:
on_street_car_parking_sensor_df["deviceid"] = pd.to_numeric(on_street_car_parking_sensor_df["deviceid"], errors="coerce")
on_street_car_parking_sensor_df["streetid"] = pd.to_numeric(on_street_car_parking_sensor_df["streetid"], errors="coerce")
on_street_car_parking_sensor_df["durationseconds"] = pd.to_numeric(on_street_car_parking_sensor_df["durationseconds"], errors="coerce")

parking_bay_arrivals_and_departures_df["parkingeventid"] = pd.to_numeric(parking_bay_arrivals_and_departures_df["parkingeventid"], errors="coerce")
parking_bay_arrivals_and_departures_df["deviceid"] = pd.to_numeric(parking_bay_arrivals_and_departures_df["deviceid"], errors="coerce")
parking_bay_arrivals_and_departures_df["durationseconds"] = pd.to_numeric(parking_bay_arrivals_and_departures_df["durationseconds"], errors="coerce")
parking_bay_arrivals_and_departures_df["bayid"] = pd.to_numeric(parking_bay_arrivals_and_departures_df["bayid"], errors="coerce")

In [41]:
on_street_car_parking_sensor_df["arrivaltime"] = pd.to_datetime(
    on_street_car_parking_sensor_df["arrivaltime"],
    errors="coerce"
)

on_street_car_parking_sensor_df["departuretime"] = pd.to_datetime(
    on_street_car_parking_sensor_df["departuretime"],
    errors="coerce"
)

on_street_parking_bay_sensor_df["lastupdated"] = pd.to_datetime(
    on_street_parking_bay_sensor_df["lastupdated"],
    errors="coerce",
    utc=True
)

on_street_parking_bay_sensor_df["status_timestamp"] = pd.to_datetime(
    on_street_parking_bay_sensor_df["status_timestamp"],
    errors="coerce",
    utc=True
)

parking_bay_arrivals_and_departures_df["arrivaltime"] = pd.to_datetime(
    parking_bay_arrivals_and_departures_df["arrivaltime"],
    errors="coerce"
)

parking_bay_arrivals_and_departures_df["departuretime"] = pd.to_datetime(
    parking_bay_arrivals_and_departures_df["departuretime"],
    errors="coerce"
)

In [42]:
on_street_car_parking_sensor_df = on_street_car_parking_sensor_df.dropna(
    subset=["deviceid", "arrivaltime", "departuretime"]
)

on_street_parking_bay_sensor_df = on_street_parking_bay_sensor_df.dropna(
    subset=["status_timestamp", "status_description", "kerbsideid"]
)

parking_bay_arrivals_and_departures_df = parking_bay_arrivals_and_departures_df.dropna(
    subset=["deviceid", "arrivaltime", "departuretime", "bayid"]
)

sign_plates_located_in_parking_bays_df = sign_plates_located_in_parking_bays_df.dropna(
    subset=["parkingzone"]
)

In [43]:
# 2014 sensor data
on_street_car_parking_sensor_df["arrival_hour"] = on_street_car_parking_sensor_df["arrivaltime"].dt.hour
on_street_car_parking_sensor_df["arrival_day"] = on_street_car_parking_sensor_df["arrivaltime"].dt.day_name()
on_street_car_parking_sensor_df["arrival_month"] = on_street_car_parking_sensor_df["arrivaltime"].dt.month
on_street_car_parking_sensor_df["is_weekend"] = on_street_car_parking_sensor_df["arrivaltime"].dt.dayofweek >= 5

# Live bay sensor data
on_street_parking_bay_sensor_df["status_hour"] = on_street_parking_bay_sensor_df["status_timestamp"].dt.hour
on_street_parking_bay_sensor_df["status_day"] = on_street_parking_bay_sensor_df["status_timestamp"].dt.day_name()
on_street_parking_bay_sensor_df["status_month"] = on_street_parking_bay_sensor_df["status_timestamp"].dt.month
on_street_parking_bay_sensor_df["is_weekend"] = on_street_parking_bay_sensor_df["status_timestamp"].dt.dayofweek >= 5

# Arrivals/departures data
parking_bay_arrivals_and_departures_df["arrival_hour"] = parking_bay_arrivals_and_departures_df["arrivaltime"].dt.hour
parking_bay_arrivals_and_departures_df["arrival_day"] = parking_bay_arrivals_and_departures_df["arrivaltime"].dt.day_name()
parking_bay_arrivals_and_departures_df["arrival_month"] = parking_bay_arrivals_and_departures_df["arrivaltime"].dt.month
parking_bay_arrivals_and_departures_df["is_weekend"] = parking_bay_arrivals_and_departures_df["arrivaltime"].dt.dayofweek >= 5

In [44]:
# Keep timestamps timezone-naive so they are easier to read and export
on_street_parking_bay_sensor_df["lastupdated"] = (
    on_street_parking_bay_sensor_df["lastupdated"].dt.tz_convert(None)
)

on_street_parking_bay_sensor_df["status_timestamp"] = (
    on_street_parking_bay_sensor_df["status_timestamp"].dt.tz_convert(None)
)

In [45]:
on_street_parking_bay_sensor_df["occupied"] = on_street_parking_bay_sensor_df["status_description"].apply(
    lambda x: 1 if x == "Present" else 0
)

on_street_parking_bay_sensor_df["occupied"].value_counts()

occupied
1    2152
0    1157
Name: count, dtype: int64

In [46]:
sign_plates_located_in_parking_bays_df = sign_plates_located_in_parking_bays_df.rename(
    columns={"parkingzone": "zone_number"}
)

sign_plates_located_in_parking_bays_df.head()

  restriction_display  zone_number time_restrictions_start restriction_days time_restrictions_finish
0                  2P         7001                07:30:00              Sat                 12:30:00
1                  2P         7007                07:30:00              Sat                 12:30:00
2                  2P         7025                07:30:00          Mon-Fri                 18:30:00
3                  2P         7025                07:30:00              Sat                 12:30:00
4                  HP         7019                07:30:00              Sat                 12:30:00

In [47]:
merged_bay_df = on_street_parking_bay_sensor_df.merge(
    sign_plates_located_in_parking_bays_df,
    on="zone_number",
    how="left"
)

print("Merged shape:", merged_bay_df.shape)
display(merged_bay_df.head())

Merged shape: (8001, 15)

,status_timestamp,zone_number,lastupdated,kerbsideid,status_description,location,status_hour,status_day,status_month,is_weekend,occupied,restriction_display,time_restrictions_start,restriction_days,time_restrictions_finish
0,2024-08-18 08:23:46,7394.0,2024-12-30 00:44:37,9344,Unoccupied,"(-37.80494402936792, 144.95916129121264)",8,Sunday,8,True,0,1P,07:30:00,Mon-Sat,18:30:00
1,2024-08-14 09:22:05,7392.0,2025-01-10 02:44:36,9373,Unoccupied,"(-37.80329074425858, 144.95836336946644)",9,Wednesday,8,False,0,2P,07:30:00,Mon-Fri,18:30:00
2,2024-08-14 09:22:05,7392.0,2025-01-10 02:44:36,9373,Unoccupied,"(-37.80329074425858, 144.95836336946644)",9,Wednesday,8,False,0,2P,07:30:00,Sat,12:30:00
3,2024-11-28 02:30:57,7084.0,2024-12-04 23:44:37,8735,Present,"(-37.80223335664963, 144.96120480793184)",2,Thursday,11,False,1,2P,07:30:00,Sat,12:30:00
4,2024-11-28 02:30:57,7084.0,2024-12-04 23:44:37,8735,Present,"(-37.80223335664963, 144.96120480793184)",2,Thursday,11,False,1,2P,07:30:00,Mon-Fri,18:30:00

In [48]:
merged_bay_df.info()
print("\nMissing values after merge:")
print(merged_bay_df.isnull().sum())

<class 'pandas.DataFrame'>
RangeIndex: 8001 entries, 0 to 8000
Data columns (total 15 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   status_timestamp          8001 non-null   datetime64[us]
 1   zone_number               7783 non-null   float64
 2   lastupdated               8001 non-null   datetime64[us]
 3   kerbsideid                8001 non-null   int64
 4   status_description        8001 non-null   str
 5   location                  8001 non-null   object
 6   status_hour               8001 non-null   int32
 7   status_day                8001 non-null   str
 8   status_month              8001 non-null   int32
 9   is_weekend                8001 non-null   bool
 10  occupied                  8001 non-null   int64
 11  restriction_display       7738 non-null   str
 12  time_restrictions_start   7738 non-null   str
 13  restriction_days          7738 non-null   str
 14  time_restrictions_finish  7738 non-null   str
dtypes: bool(1), datetime64[us](2), float64(1), int32(2), int64(2), object(1), str(6)
memory usage: 820.5+ KB

Missing values after merge:
status_timestamp              0
zone_number                 218
lastupdated                   0
kerbsideid                    0
status_description            0
location                      0
status_hour                   0
status_day                    0
status_month                  0
is_weekend                    0
occupied                      0
restriction_display         263
time_restrictions_start     263
restriction_days            263
time_restrictions_finish    263
dtype: int64

In [49]:
# We need zone_number for grouping, so remove rows where it is missing
merged_bay_df = merged_bay_df.dropna(subset=["zone_number"])

# Fill restriction details so downstream analysis has readable values
merged_bay_df["restriction_days"] = merged_bay_df["restriction_days"].fillna("Unknown")
merged_bay_df["restriction_display"] = merged_bay_df["restriction_display"].fillna("Unknown")
merged_bay_df["time_restrictions_start"] = merged_bay_df["time_restrictions_start"].fillna("Unknown")
merged_bay_df["time_restrictions_finish"] = merged_bay_df["time_restrictions_finish"].fillna("Unknown")

After merging the parking bay sensor data with the parking restriction data, some missing values were found. Rows with missing zone numbers were removed because zone information is necessary for grouping and demand analysis. Missing restriction-related fields were filled with "Unknown" so that the dataset remains usable and easier to interpret.

In [50]:
# Group occupancy by zone, day, hour, and weekend status
demand_df = (
    merged_bay_df.groupby(
        ["zone_number", "status_day", "status_hour", "is_weekend"],
        as_index=False
    )["occupied"].mean()
)

demand_df = demand_df.rename(columns={"occupied": "average_occupancy"})

display(demand_df.head())
print("Demand dataset shape:", demand_df.shape)

   zone_number status_day  status_hour  is_weekend  average_occupancy
0       7010.0     Friday            1       False                0.0
1       7010.0   Thursday           21       False                1.0
2       7010.0   Thursday           22       False                1.0
3       7010.0   Thursday           23       False                1.0
4       7010.0  Wednesday            9       False                0.0

Demand dataset shape: (1715, 5)

In [51]:
def demand_level(value):
    if value < 0.33:
        return "Low"
    elif value < 0.66:
        return "Medium"
    else:
        return "High"

demand_df["demand_level"] = demand_df["average_occupancy"].apply(demand_level)

demand_df.head()

   zone_number status_day  status_hour  is_weekend  average_occupancy demand_level
0       7010.0     Friday            1       False                0.0          Low
1       7010.0   Thursday           21       False                1.0         High
2       7010.0   Thursday           22       False                1.0         High
3       7010.0   Thursday           23       False                1.0         High
4       7010.0  Wednesday            9       False                0.0          Low

In [52]:
print("Statistical summary of demand dataset:")
print(demand_df.describe())

Statistical summary of demand dataset:
       zone_number  status_hour  average_occupancy
count  1715.000000  1715.000000        1715.000000
mean   7464.381924     9.433819           0.627788
std     243.424799     6.287512           0.453420
min    7010.000000     0.000000           0.000000
25%    7246.000000     5.000000           0.000000
50%    7455.000000     9.000000           1.000000
75%    7634.000000    11.000000           1.000000
max    7995.000000    23.000000           1.000000

In [53]:
print("Missing values in cleaned demand_df:")
print(demand_df.isnull().sum())

Missing values in cleaned demand_df:
zone_number          0
status_day           0
status_hour          0
is_weekend           0
average_occupancy    0
demand_level         0
dtype: int64

In [54]:
# Save processed files
merged_bay_df.to_csv("../data/processed/merged_bay_sensor_data.csv", index=False)
demand_df.to_csv("../data/processed/cleaned_demand_data.csv", index=False)

print("Files saved successfully.")

Files saved successfully.

The cleaned dataset now represents average parking occupancy by zone, day, hour, and weekend status. This makes it suitable for later exploratory data analysis and for building a model to classify parking demand as low, medium, or high.